---
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-unpoller
  namespace: flux-system
spec:
  path: ./kubernetes/monitoring/unpoller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  postBuild:
    substituteFrom: []
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: monitoring-prometheus-stack
