apiVersion: v1
kind: Secret
metadata:
    name: docker-registry
    namespace: dev-nuclio
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: dev-n8n
data:
    .dockerconfigjson: ENC[AES256_GCM,data:b2UTSBGdrIZx2hAoeAcR9lQRGaQNguuVdkCAgU5hHZWWonPltMe96WtqIBtIwNdstc+BtM5eBoPDsu6SyqJtbHXJk7xxfEuMdgS4CCxRaboekE7B9yC7JzawJ1bEFWa8Dr+bZ21g1EaO2smrkrjnww0RFp7kUiA2kmgaZCcAmyq+U/jlmFtGHAIoy5aU0FQi3kqNnzU4B6fVhnDtjeRLvQ==,iv:7Z5ZRJTivMN9GMsJXhj2TauWDRZo3nGuKmHXJB+c57o=,tag:E5upSmvW7X+ZLOHG6uq+GA==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T03:25:56Z"
    mac: ENC[AES256_GCM,data:n9we3diA+ZtENjQMDd8e7e7arjSICR+21Mfmi9SnVPhPrpBgk1X7d356dH4CXwj07m3z4Xv7WJzlv49KA2kFIRj/hpVA8pdf501z6VVqKQOcCbiJc04pf2ZHsKl/B3sc7awc8hFe83THaLFI3lROVlBcomfXWGXW3SA1NxP768s=,iv:dgqqbQB0ks7asVYY1bsOcheei3wEHvxL67aLRWIXiY8=,tag:biFYa2HUAi8rUrtIKgZk1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
