apiVersion: v1
kind: Secret
metadata:
    name: nuclio-secrets
    namespace: dev-nuclio
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: dev-n8n
stringData:
    docker-username: ENC[AES256_GCM,data:7rvo8nQ8q1kQBsSvGQ==,iv:VB1IMTjkMCjSZZDGzGoMjo7kVO07uLI7+z9S6ruZHPo=,tag:MnJ+M5F/aix7qCgJQ+VZUg==,type:str]
    docker-password: ENC[AES256_GCM,data:TGgkpOPH4jcuQ1NIMFKVRZdVPa8l0PJoQzhlzJSoe3U=,iv:1YeZRW3IZU1zeDIA+tB4H8wnqhufT0vKkawWYa8ta+I=,tag:21l1UCi1+MwqVDYfY2v6nw==,type:str]
    docker-server: ENC[AES256_GCM,data:8A1QOWfyuRcbX/yG+bkoPQdrK0AmZvF292P6VA==,iv:AsFsD61bgHnlkGrrwGeZykEPopWYl7/btl9NuwDMAQc=,tag:5FOJSlEJabrWOfLh4+7kAg==,type:str]
    docker-email: ENC[AES256_GCM,data:RvjFV3xu68pigU/eVXDbP+k=,iv:gOetKAp4ZHhyGxcc8QWjWu0mgU9ng9nBl9FNymooczs=,tag:+J7W8/Fz0mHkzWg3jUvQfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T02:06:55Z"
    mac: ENC[AES256_GCM,data:oWDUFTh6cWKmOD9h//cf07Hg2C9ShP41vqygIPPiubafCo3fDw1FkW0bsr5JXpD8NcBOhZ0gzvkLubW73Lfsp/hnonLFzao23Q5kXuRz3FX8oJDbOYhcBCCX0KM+oA60TUENKYB3oyZTjhuSAiRQC99/SWefMAR4UwWXTTbfOBU=,iv:KgLbOO3wuqb220u5oS/NTIHtph7HsTWmKKavQQppUSY=,tag:gpESpIFl/0TfIluTGvEOjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
