apiVersion: v1
kind: Secret
metadata:
    name: ${APP}
    namespace: ${NS}
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "false"
stringData:
    username: ENC[AES256_GCM,data:AkplFriO97IgQAkCdZ5hYczqjQ==,iv:gyC8RWrdhv0KsUiBR8/XhWmbDGDD9zRqyAWd+0KzgFs=,tag:7fTWcnNGyUtSOFQMQBQkgg==,type:str]
    password: ENC[AES256_GCM,data:fffgJCRpSypQ98eM/v9Y4g==,iv:9v4fxwqX4RiN8hISDBweYm0hVII9P2HysqNBpox56Co=,tag:+e+gbzDrz/tu9hkw06oJbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T22:35:43Z"
    mac: ENC[AES256_GCM,data:78/5K7l2cXzYre7J2YcAUNT+686AbxvFtYgGlATyGkGeBRgx4EZAWvZDG3PWDAKBV920JLYk+VWyCcyNgkF5BuPTYO4LkRgDlSu+qkW0O6K+6IPyJ0od1kuh2bC9txWzfx2dliLmMe3OkssLjendFtaM7LWznNO14ZZ7VtUGFe4=,iv:mHx2dGSwD424YwSOk31I2WJUhFUROddKmeJXjhkqu1U=,tag:JRgx0ntpsvlbQw8jOq3yNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
