---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: iot-vlan
  namespace: network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "iot-vlan",
      "plugins": [
        {
          "type": "macvlan",
          "master": "enp2s0.50",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "192.168.255.0/24",
                "gw": "192.168.255.1"
              }
            ],
            "gateway": [
              "192.168.255.1"
            ],
            "capabilities": { "mac": true }
          }
        }
      ]
    }
# ---
# apiVersion: k8s.cni.cncf.io/v1
# kind: NetworkAttachmentDefinition
# metadata:
#   name: macvlan-net
# spec:
#   config: |-
#     {
#       "cniVersion": "0.3.1",
#       "type": "macvlan",
#       "mode": "bridge",
#       "master": "eth0",
#       "ipam": {
#         "type": "host-local",
#         "subnet": "192.168.1.0/24",
#         "rangeStart": "192.168.1.200",
#         "rangeEnd": "192.168.1.250",
#         "routes": [
#           { "dst": "0.0.0.0/0" }
#         ],
#         "gateway": "192.168.1.1"
#       }
#     }
