apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage-minio
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:5BI4JbE=,iv:5sy2WLkAGPfFJ3GauRQABzVmdDQTj8PCeZFq1F+VFek=,tag:Cw33kwLqCSc2gKCy8S16Yw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:OEW2asPrDc4=,iv:8hg9/OdD9mkD4n3MO43U2L17wtWdr3/Tb8f41YO6sQI=,tag:KmAynmHyIitWBlIL4R4+ew==,type:str]
    VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:s0rOpePf8ngr,iv:oYRA+d4vb62P8hONUMUC56zNneKi20ILMXWDXxTU5Rc=,tag:EiDEwD/XNHxrP3N8+Lt3aQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T18:31:26Z"
    mac: ENC[AES256_GCM,data:e15uZOvaTjeUVbTN9NnvLzeg3o5mDBE17V9bAJjFfLmprjawb7KWM+ePS3BWw2YBvSf6coCfOsIi3cnxRLWtt+WsaZbHcrcsSAx+HbvkqOzj0y0shmTl2H7fEOAeVXfJSYYswuyA5PRP4D8XTxTJ1U+RYg7eyEfzY7tuN4fFw2Q=,iv:PFARJW245VjT2Z+pa1Gl1jJ2KqPMIklvTnNvKGPQeNo=,tag:TlKlHsJRt6wG7uidpHWMfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
