---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    controllers:
      renovate:
        annotations:
          reloader.stakater.com/auto: 'true'
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.5
            envFrom: &envFrom
              - secretRef:
                  name: &db cnpg-pg-main-secret
              - secretRef:
                  name: &secrets renovate-secret

        containers:
          app:
            nameOverride: renovate
            image:
              repository: ghcr.io/mend/renovate-ce
              tag: '10.2.0'
              
            envFrom: *envFrom

            env:
              TZ: '${TIMEZONE}'
              LOG_LEVEL: info

              MEND_RNV_ACCEPT_TOS: 'y'
              MEND_RNV_PLATFORM: 'github'
              MEND_RNV_CRON_JOB_SCHEDULER_ALL: '* 16-23/1 * * *'
              MEND_RNV_CRON_APP_SYNC: "* 16-23/1 * * *"

              RENOVATE_PAGINATE_ALL: "true"

              MEND_RNV_ADMIN_API_ENABLED: 'true'
              MEND_RNV_REPORTING_ENABLED: "true"

              MEND_RNV_WORKER_CLEANUP: '* 00-03/1 * * 6'
              MEND_RNV_WORKER_CLEANUP_DIRS: '/opt/containerbase,/tmp/renovate/cache,/tmp/renovate/repos'

              MEND_RNV_DATA_HANDLER_TYPE: postgresql
              # MEND_RNV_LOG_HISTORY_S3: 's3://renovate/log'

              PGHOST: &db_host
                valueFrom:
                  secretKeyRef:
                    name: *db
                    key: INIT_POSTGRES_HOST
              PGPORT: &db_port
                valueFrom:
                  secretKeyRef:
                    name: *db
                    key: INIT_POSTGRES_PORT

              # MEND_RNV_S3_FORCE_PATH_STYLE: 'true'

              RENOVATE_ALLOW_CUSTOM_CRATE_REGISTRIES: 'false'
              RENOVATE_ALLOW_PLUGINS: 'false'

              RENOVATE_AUTODISCOVER: 'true'
              RENOVATE_ONBOARDING: 'true'

              RENOVATE_REDIS_URL: 'redis://dragonfly.database.svc.cluster.local:6379/0'
              # RENOVATE_REPOSITORY_CACHE: 'enabled'
              # RENOVATE_REPOSITORY_CACHE_TYPE: 's3://renovate/cache/'
              # RENOVATE_X_S3_PATH_STYLE: 'true'

            probes:
              liveness: &probe
                type: HTTP
                path: /health
              readiness: *probe
              startup: *probe

            resources:
              requests:
                cpu: 100m
              limits:
                cpu: 1000m

    service:
      app:
        controller: renovate
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: renovate.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        type: configMap
        name: renovate-config
        globalMounts:
          - path: /usr/src/app/config.js
            readOnly: true
            subPath: config.js

      cache-persistence:
        enabled: true
        type: emptyDir
        sizeLimit: 4Gi
        globalMounts:
          - path: '/tmp/renovate'

      tmp:
        enabled: true
        type: emptyDir
