---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1wnxm438gfmv6kg658crenxxzad3krnytqqdlseyues9um26meyus7cnla9"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1wnxm438gfmv6kg658crenxxzad3krnytqqdlseyues9um26meyus7cnla9"
