---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-n8n
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/home/n8n/app
  targetNamespace: &ns home-n8n
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app n8n
      app.kubernetes.io/group: home

  postBuild:
    substitute:
      APP: *app
      NS: *ns
      VOLSYNC_CLAIM: n8n-config
      VOLSYNC_CAPACITY: 5Gi
      # PG_MAIN_CREDS: postgres-critical-secret
      PG_MAIN_CREDS: cnpg-pg-main-secret
      #PG_SECRET: *app
      PG_SECRET: n8n-secrets
      PG_NAME: home-assistant
      PG_USER: home-assistant

  components:
    - ../../../components/volsync
    - ../../../components/ns

  interval: 1h
  prune: true
  retryInterval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn: []

