---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-prom
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: opentelemetry-collector
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: opentelemetry-targetallocator-cr-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-discovery
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: opentelemetry-collector
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: opentelemetry-targetallocator-role
  apiGroup: rbac.authorization.k8s.io
