apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest
  namespace: monitoring
spec:
  mode: statefulset
  serviceAccount: opentelemetry-collector
  targetAllocator:
    image: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:main
    enabled: true
    allocationStrategy: per-node
    serviceAccount: opentelemetry-collector
    prometheusCR:
      enabled: true
      serviceMonitorSelector:
        matchExpressions:
          - key: app
            operator: In
            values: ["my-app"]
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 30s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]

    exporters:
      logging:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [logging]
