apiVersion: v1
kind: Secret
metadata:
    name: cnpg-main17-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: home,monitoring,dev,test,media
stringData:
    host: ENC[AES256_GCM,data:13Ns3j/0zoDgWabE5dCbRUf61toqOLfiq3qZ3BC7FR3EA+r/AdqMkS7Pj55p,iv:EU9wOAGKy28MX1camIWfDGjy22U6bhOH4rU/6ALQ42Q=,tag:dS2dXpHpyfzDvaRR0KdEfg==,type:str]
    port: ENC[AES256_GCM,data:KirkDA==,iv:pa95QP48p+IK3pSGl4O1OrqhnPt8VWXG9pEEQxfqjWM=,tag:r0mrgWF9uESRvPZCs4UVVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T15:52:02Z"
    mac: ENC[AES256_GCM,data:PxQtYiS7VqsqmuE3xJfGuarjAAem/JWxHv4dbKeJemovHoL/hiAifkgGlVN9+HoIEtmIDLlL1pmlHDYuaE780B4F/oixCDWoCJQoeiBMZ0Srlatj5RdXLc7YpOBAPshbG+5bZIKamvFgBDgovaqECn0kZQmVhwIzvJ+ueQw6Y0Y=,iv:gC4UIazFrir7CwqcvjkU7utj+FOQy3UKHt883jA9YwE=,tag:hs4txELeBvG9IfZAPM5mcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
