apiVersion: v1
kind: Secret
metadata:
    name: cnpg-main17-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: home,monitoring,dev,test,media
stringData:
    host: ENC[AES256_GCM,data:fmCtNwm7uBYefYEzx1pgJrkCQ5McFz6NA8QpaWy1QYMYZIjJ4BCKB63hEdwQ,iv:NtWUQOm0b9B+MkHiYbMw8lZDbDVurerKSgS3Tu///Qk=,tag:cmsYGFvANFYXkTA1hP6idA==,type:str]
    port: ENC[AES256_GCM,data:KirkDA==,iv:pa95QP48p+IK3pSGl4O1OrqhnPt8VWXG9pEEQxfqjWM=,tag:r0mrgWF9uESRvPZCs4UVVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T15:58:49Z"
    mac: ENC[AES256_GCM,data:w2slapiEGmodi+LLtSA4ppn06CnJPBNNUL4lZbLsFSk3du0On7UHIjJ25zWsJzzbKyyTlaDEi5pX5LjYBiL3/vNOtk2NncUVMFUN3LMwRmaQn3yeAL/SVHiFn1g4F2n2E5ma8hJqKn7eEao7wQLnR4JE1absYyd96Xr6+q7pie4=,iv:F13TMMliKGFzlvizkh1SEuyKvHcfm3o4F8SAkuOHSV0=,tag:Q27ChMOmTq2ZjSpSdlYTVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
