apiVersion: v1
kind: Secret
metadata:
    name: cnpg-main17-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    host: ENC[AES256_GCM,data:fmCtNwm7uBYefYEzx1pgJrkCQ5McFz6NA8QpaWy1QYMYZIjJ4BCKB63hEdwQ,iv:NtWUQOm0b9B+MkHiYbMw8lZDbDVurerKSgS3Tu///Qk=,tag:cmsYGFvANFYXkTA1hP6idA==,type:str]
    port: ENC[AES256_GCM,data:KirkDA==,iv:pa95QP48p+IK3pSGl4O1OrqhnPt8VWXG9pEEQxfqjWM=,tag:r0mrgWF9uESRvPZCs4UVVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T01:00:14Z"
    mac: ENC[AES256_GCM,data:YmRFMJYKUrnziqlIKY438j0f8B6TrCW/0SaSDU50X4swuChc83lsxN+my+OfaakissguhL0ECR3wvDK2OB+lXhIDNEq6ewmr9bof68MscIhcB5EZiJcM0hagpUymhgces+w4b5A8yqxHoMRVrbdOLtB9Bu8DLfV6DLzkaYwZDek=,iv:ACXf6ioVcUjsDvPOZudYU8ct8nYXTx4wmGvJoPvGz/4=,tag:eezLFgWAlYacmxTqLlpCEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
