---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-clickhouse-operator
  namespace: flux-system
spec:
  targetNamespace: &ns database-clickhouse
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app clickhouse-operator
  dependsOn:
    # - name: external-secrets-stores
    - name: cluster-storage
    - name: cluster-network
  path: ./kubernetes/database/clickhouse/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      NS: *ns
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-clickhouse-main
  namespace: flux-system
spec:
  targetNamespace: &ns database-clickhouse
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app clickhouse-main
  dependsOn:
    - name: database-clickhouse-operator
  path: ./kubernetes/database/clickhouse/main
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      NS: *ns
