---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: snapshot-controller
      namespace: kube-system
  values:
    manageCRDs: true
    image: &image
      # The stock image is not yet multi-arch
      # https://github.com/backube/volsync/issues/828
      repository: &image ghcr.io/onedr0p/volsync
      tag: &tag 0.12.0
    rclone:
      repository: *image
      tag: *tag
    restic:
      repository: *image
      tag: *tag
    metrics:
      disableAuth: true
