---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: observability-ec31
  namespace: rook-ceph
spec:
  metadataPool:
    enableRBDStats: true # Enable RBD stats for monitoring
    failureDomain: osd
    replicated:
      size: 3
      requireSafeReplicaSize: true # Requires 3 OSDs
      hybridStorage:
        primaryDeviceClass: nvme
        secondaryDeviceClass: hdd
    parameters:
      pg_autoscale_mode: "on"
      min_size: "2" # Minimum number of replicas required for writes

  dataPool:
    enableRBDStats: true # Enable RBD stats for monitoring
    failureDomain: osd
    erasureCoded:
      dataChunks: 3
      codingChunks: 1 # Requires 4+ OSDs to become active
    parameters:
      pg_autoscale_mode: "on"
      bulk: "true"
      fast_read: "true"

  preservePoolsOnDelete: false # delete pools

  gateway:
    port: 80 # Or 443 if using SSL
    instances: 1 # Start with 1, increase later if needed for performance/HA
    resources: {} # Define if needed
    hostNetwork: false
    priorityClassName: system-cluster-critical

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ceph-objectstore-observability-ec31
  namespace: rook-ceph # namespace:cluster
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
spec:
  rules:
    - host: observability.rgw.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            backend:
              service:
                name: rook-ceph-rgw-observability-ec31
                port:
                  number: 80
            pathType: "Prefix"
  ingressClassName: internal

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-bucket-observability-ec31
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Retain
volumeBindingMode: "Immediate"
parameters:
  objectStoreName: observability-ec31
  objectStoreNamespace: rook-ceph
  region: eu-central-1
    # RBD image format. Defaults to "2".
  imageFormat: "2"

  # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
  # imageFeatures: layering
  imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock

# ---
# apiVersion: ceph.rook.io/v1
# kind: CephObjectStore
# metadata:
#   name: observability-ec21
#   namespace: rook-ceph
# spec:
#   metadataPool:
#     enableRBDStats: true # Enable RBD stats for monitoring
#     failureDomain: osd
#     replicated:
#       size: 3
#       requireSafeReplicaSize: true # Requires 3 OSDs
#       hybridStorage:
#         primaryDeviceClass: nvme
#         secondaryDeviceClass: hdd
#     parameters:
#       pg_num_min: "8"
#       pg_num: "8"
#   dataPool:
#     enableRBDStats: true # Enable RBD stats for monitoring
#     failureDomain: osd
#     erasureCoded:
#       dataChunks: 2
#       codingChunks: 1 # Requires 4+ OSDs to become active
#     parameters:
#       pg_num_min: "8"
#       pg_num: "8"
#     # deviceClass: hdd

#   preservePoolsOnDelete: false # delete pools

#   gateway:
#     port: 80 # Or 443 if using SSL
#     instances: 1 # Start with 1, increase later if needed for performance/HA
#     resources: {} # Define if needed
#     hostNetwork: false
#     priorityClassName: system-cluster-critical

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ceph-objectstore-observability-ec21
#   namespace: rook-ceph # namespace:cluster
#   annotations:
#     external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
#     nginx.ingress.kubernetes.io/proxy-body-size: "0"
#     nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
# spec:
#   rules:
#     - host: observability-ec21-rgw.${SECRET_DOMAIN}
#       http:
#         paths:
#           - path: /
#             backend:
#               service:
#                 name: rook-ceph-rgw-observability-ec21
#                 port:
#                   number: 80
#             pathType: "Prefix"
#   ingressClassName: internal

# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: ceph-bucket-observability-ec21
# provisioner: rook-ceph.ceph.rook.io/bucket
# reclaimPolicy: "Delete"
# volumeBindingMode: "Immediate"
# parameters:
#   objectStoreName: observability-ec21
#   objectStoreNamespace: rook-ceph
#   region: eu-central-1
