---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# system
  - ./system/bjw-s.yaml
  - ./system/cilium.yaml
  - ./system/metrics-server.yaml
# network
  - ./network/jetstack.yaml
  - ./network/ingress-nginx.yaml
  - ./network/external-dns.yaml
  - ./network/k8s-gateway.yaml
  - ./network/stakater.yaml
# monitoring
  - ./monitoring/prometheus-community.yaml
  - ./monitoring/kubernetes-dashboard.yaml
  - ./monitoring/grafana.yaml
  - ./monitoring/intel.yaml
  - ./monitoring/node-feature-discovery.yaml
  - ./monitoring/opentelemetry-charts.yaml
# storage
  - ./storage/openebs.yaml
  - ./storage/rook-ceph.yaml
  - ./storage/longhorn.yaml
# database
  - ./database/emqx.yaml
  - ./database/cloudnative-pg.yaml
# test
  - ./test/podinfo-source.yaml
