---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
# network
  - ./jetstack.yaml
  - ./ingress-nginx.yaml
  - ./external-dns.yaml
  - ./k8s-gateway.yaml
  - ./stakater.yaml
# system
  - ./cilium.yaml
  - ./metrics-server.yaml
# monitoring
  - ./kubernetes-dashboard.yaml
# storage
  - ./openebs.yaml
