---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-nvidia-gpu-operator
  namespace: flux-system
spec:
  targetNamespace: kube-system
  path: ./kubernetes/system/nvidia-gpu-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: nvidia-gpu-operator
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
