apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:UL9F3BsUv3YGQ1p4O6sy3wn86ifLjHxu+xVEJru3Taz97pmX,iv:w5n9hkgHGutPGyrtvI2mIvC4kQOyxzVO4m4uJaVRsxE=,tag:cMFvVK+j49g+kQOKsXHVMg==,type:str]
    credentials.json: ENC[AES256_GCM,data:9WS8YJAAj2WkLTmVb3eXUCkFlxhJvhmpg4T/AZgyPRQYj4jv3fNlsCwQevEc/mY4PGu/VZEVmp7N0zAaY0gOIL2w1Z8VK2lYSbNUv8k0ZtfQvKGZxqX/7F1Ztp7CX41UbckbpUaJVwQlOpyO9ioyecsaddRtiWDnw1cv7WQQ7tPs0+HEzw7I6vxFwMamjet4b8P3SXfS5ALYuXEUl6dSt118toTdI5brazn+FXUatw==,iv:lG01h8lbZE5THEYOSJc4D897t7OC6q9A7XAoUnGDTXU=,tag:tvc9Npk8GaERNg5lFgXzmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRVMwR3paMnBWUkI2SWVO
            M0pnRVB3ejRaQUZ6UUliKzliNGl0bTF0QjI0CnR5RDdzSWRXdHhibVZLdllkd3FR
            cVVpUXg1bzI0QzAxYkpvRUFxcWVxQjgKLS0tIEkwY0pCQnpwbUNJUHRrcmJscURh
            N1NDRWtYWUovV0MvdnBXenNMSEhpOGcKUH0a/hFMO57UwDdPHlH7BSgU7i+MYXwt
            EMXBJEAAb/F6kmuqWRBO/FWX7w5+7xOofO8AzoOX54bWWgiR5xM5cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T17:12:40Z"
    mac: ENC[AES256_GCM,data:GAeOGB6qM687/0Ka4yGJBpQPrlN+zECyVVQQQU3xDJzDCEMyPpuHDnyezcFDrtYMoDdTXR53Sztq+7HCG93baZnyuHOgfRRs0B330OW1j///bQpS5jEFd241YPf6yKBLrhDsf2bBwHGc8FclMPw4i92mn4J1c1HQjrPpO0ciQxQ=,iv:n6y7wFagBZwYLB1edzfUMyhUKCZb3GO07r6bNSCMp0o=,tag:hNgQpRdMIVz+d2YQim1Ulw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
