---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ingress-nginx-certificates
  namespace: flux-system
  labels: &ll
    substitution.flux.home.arpa/disabled: "true"
    kustomization.flux.home.arpa/default: "true"
    kustomization.flux.home.arpa/helmpatches: "true"
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: network-cert-manager-issuers
  path: ./kubernetes/network/ingress-nginx/certificates
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ingress-nginx-internal
  namespace: flux-system
  labels: &ll
    substitution.flux.home.arpa/disabled: "true"
    kustomization.flux.home.arpa/default: "true"
    kustomization.flux.home.arpa/helmpatches: "true"
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: network-ingress-nginx-certificates
  path: ./kubernetes/network/ingress-nginx/internal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ingress-nginx-external
  namespace: flux-system
  labels: &ll
    substitution.flux.home.arpa/disabled: "true"
    kustomization.flux.home.arpa/default: "true"
    kustomization.flux.home.arpa/helmpatches: "true"
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: network-ingress-nginx-certificates
  path: ./kubernetes/network/ingress-nginx/external
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ingress-nginx-dashboard
  namespace: flux-system
  labels: &ll
    substitution.flux.home.arpa/disabled: "true"
    kustomization.flux.home.arpa/default: "true"
    kustomization.flux.home.arpa/helmpatches: "true"
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/network/ingress-nginx/dashboard
