---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph
      version: v1.18.1
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system

  maxHistory: 3

  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    # logLevel: DEBUG
    annotations:
      configmap.reloader.stakater.com/reload: rook-ceph-operator-config

    crds:
      enabled: true

    csi:
      provisionerReplicas: 3
      provisionerNodeAffinity: ceph.rook.io/cluster=enabled;  #key1=value1,value2; key2=value3
      pluginNodeAffinity: ceph.rook.io/cluster=enabled; #node-role.kubernetes.io/storage-node=true #key1=value1,value2; key2=value3

    nfs:
      # -- Enable the nfs csi driver
      enabled: true

      # logLevel: 5

    topology:
      # -- Enable topology based provisioning
      enabled: false
      # NOTE: the value here serves as an example and needs to be
      # updated with node labels that define domains of interest
      # -- domainLabels define which node labels to use as domains
      # for CSI nodeplugins to advertise their domains
      domainLabels:
      # - kubernetes.io/hostname
      # - topology.kubernetes.io/zone
      # - topology.rook.io/rack

    # -- Enable discovery daemon
    enableDiscoveryDaemon: true
    # -- Set the discovery daemon device discovery interval (default to 60m)
    discoveryDaemonInterval: 60m

    discover:
      # -- Toleration for the discover pods.
      # Options: `NoSchedule`, `PreferNoSchedule` or `NoExecute`
      toleration:
      # -- The specific key of the taint to tolerate
      tolerationKey:
      # -- Array of tolerations in YAML format which will be added to discover deployment
      tolerations:
      #   - key: key
      #     operator: Exists
      #     effect: NoSchedule
      # -- The node labels for affinity of `discover-agent` [^1]
      nodeAffinity:
      #   key1=value1,value2; key2=value3
      #
      #   or
      #
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #       - matchExpressions:
      #           - key: storage-node
      #             operator: Exists
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/storage-node # Label specific to your main storage node(s)
              operator: Exists

      # -- Labels to add to the discover pods
      podLabels: # "key1=value1,key2=value2"

      # -- Add resources to discover daemon pods
      resources:

      #   - limits:
      #       memory: 512Mi
      #   - requests:
      #       cpu: 100m
      #       memory: 128Mi

    pspEnable: false

    monitoring:
      enabled: true

    resources:
      requests:
        cpu: 10m
        memory: 400M
      limits:
        memory: 400M

    serviceMonitor:
      # -- Enable ServiceMonitor for Ceph CSI drivers
      enabled: true
