---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph
      version: v1.16.5
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system

  maxHistory: 3

  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    # logLevel: DEBUG
    annotations:
      configmap.reloader.stakater.com/reload: rook-ceph-operator-config

    crds:
      enabled: true

    csi:
      provisionerReplicas: 3
      provisionerNodeAffinity: ceph.rook.io/cluster=enabled;  #key1=value1,value2; key2=value3
      pluginNodeAffinity: ceph.rook.io/cluster=enabled; #node-role.kubernetes.io/storage-node=true #key1=value1,value2; key2=value3

      # logLevel: 5

    pspEnable: false

    monitoring:
      enabled: true

    resources:
      requests:
        cpu: 10m
        memory: 400M
      limits:
        memory: 400M

