---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app librechat
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/ai/librechat/app
  targetNamespace: &ns ai-librechat
  components:
    - ../../templates/volsync_new
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: *app
      NS: *ns
      VOLSYNC_CLAIM: librechat-zfs
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_STORAGECLASS: hl-zfs-pv
