---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ai-librechat
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/ai/librechat/app
  targetNamespace: &ns ai-librechat
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app librechat
      app.kubernetes.io/group: ai

  postBuild:
    substitute:
      APP: *app
      NS: *ns
      DB_MAIN_SECRET: cnpg-pg-main-secret
      DB_SECRET: librechat-secrets
      DB_NAME: ai-librechat
      DB_USER: ai-librechat

  components:
    - ../../../components/volsync
    - ../../../components/ns

  interval: 1h
  prune: true
  retryInterval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn: []

