---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app thanos
  namespace: flux-system
  labels: &ll
    kustomization.flux.home.arpa/default: "true"
    kustomization.flux.home.arpa/helmpatches: "true"
    substitution.flux.home.arpa/disabled: "false"
    prune.flux.home.arpa/disabled: "false"
    wait.flux.home.arpa/disabled: "false"
    storage.flux.home.arpa/required: "true"
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: storage-rook-ceph-cluster
  path: ./kubernetes/monitoring/thanos/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
