---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-thanos
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/monitoring/thanos/app
  targetNamespace: &ns monitoring-thanos
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app thanos
      app.kubernetes.io/group: monitoring

  postBuild:
    substitute:
      APP: *app
      NS: *ns
      StorageClass: ceph-fs-observability-ec31

  components:
    - ../../../components/ns

  interval: 1h
  prune: true
  retryInterval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: storage-rook-ceph-cluster
