# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  - name: volsync
    namespace: storage
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            env:
              INIT_POSTGRES_DBNAME:
                valueFrom:
                  secretKeyRef:
                    name: home-assistant-db-secret
                    key: name
              INIT_POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: home-assistant-db-secret
                    key: user
              INIT_POSTGRES_PASS:
                valueFrom:
                  secretKeyRef:
                    name: home-assistant-db-secret
                    key: password
              INIT_POSTGRES_HOST:
                valueFrom:
                  secretKeyRef:
                    key: host
                    name: main16-secret
              INIT_POSTGRES_SUPER_PASS:
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: cloudnative-pg-secret
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.7.3@sha256:49edf11a71f1c6b8787dc5b190252d7a2e72e40d93091011be26d2162b1cdff6
            env:
              TZ: &TZ ${TIMEZONE}
              HASS_EXTERNAL_URL: https://hass.${SECRET_DOMAIN}
              HASS_INTERNAL_URL: https://hass.${SECRET_DOMAIN}
              HASS_TRUSTED_PROXIES: ${NODE_CIDR}
              HASS_HTTP_TRUSTED_PROXY_1: ${NODE_CIDR}
              HASS_HTTP_TRUSTED_PROXY_2: ${CLUSTER_CIDR}
              SERVER_HOST:
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              DB_HOST:
                valueFrom:
                  secretKeyRef:
                    key: host
                    name: main16-secret
              HASS_RECORDER_DB_URL: "postgresql://$(DB_user):$(DB_password)@$(DB_HOST)/home_assistant"
            envFrom: &envFrom
            - prefix: "DB_"
              secretRef:
                name: home-assistant-db-secret
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.89.1@sha256:01dfb4784e1deefe15c8d09930520bb7074e2feddbc5128e82a3e3ee57f6bcff
            env:
              TZ: *TZ
            envFrom: *envFrom
            args:
            - "/config"
            - --auth
            - "none"
            - --user-data-dir
            - "/config/.vscode"
            - --extensions-dir
            - "/config/.vscode"
            resources:
              limits:
                memory: 256Mi
              requests:
                cpu: 10m
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
    service:
      app:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${HOME_ASSISTANT_IP}
        controller: home-assistant
        ports:
          http:
            primary: true
            port: 8123
          codeserver:
            port: 8080
            # dnla-udp:
            #   enabled: true
            #   port: 1900
            #   protocol: UDP
            #   targetPort: 1900
            #   nodePort: 1900
            # bonjour-udp:
            #   enabled: true
            #   port: 5353
            #   protocol: UDP
            #   targetPort: 5353
            #   nodePort: 5353
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
        - host: &host hass.${SECRET_DOMAIN}
          paths:
          - path: /
            service:
              identifier: app
              port: http
        - host: &codeserverHost "hass-code.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              identifier: app
              port: codeserver
        tls:
        - hosts:
          - *host
          - *codeserverHost

    persistence:
      config:
        existingClaim: home-assistant
      # secrets.yaml:
      #   items:
      #   - key: secrets.yaml
      #     path: /config/secrets.yaml
      #   name: home-assistant-secret
      logs:
        type: emptyDir
        globalMounts:
        - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
        - path: /config/tts
      tmp:
        type: emptyDir
