apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: home
data:
    secrets.yaml: ENC[AES256_GCM,data:ZhOvtSf0v3yBa9NMFunbyDsJQYd92PfPaB8VFyZe7mkBRbUIK565ItF49NcUpST4FetAhIwA8rLZyApb7yubS87/yiCxuHzFQhv0ufUNk52SAyN4OGpDyqLFHys8DLsl/UEVkgFQvxsO/fnt1dtAgnDdXGX4V5sRGi+1VvND917C5XNtqFQibKzHE2uT18fBVJTW6TZB/TcKwKz6iG7ua8LIrfFq,iv:ojcWbJhdhmDu+RX1Ayr435tAM+512G4M08qdGGWG23U=,tag:8PvXWYSWfegC1Y0wUOp7pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T15:46:20Z"
    mac: ENC[AES256_GCM,data:PzGijzFDw0aPBHAeRyM2Jq9pwc7J0uLWCYC0F/zUHbUOrPOGuVUyMw/3IxlFi7S1r6xEKSie3iYdpqQGcmHrEsI0HaTQNbe2P1MzuZglRuvZITQxkcttM0MV2RMOz5fbApNfjqaQNqzcdVbGTUNIft8s37dHRtqluS7Ckib9fSI=,iv:Ykn5AqJJKwc5LVjH83sik5LcSgZDsFV/1lucX0nE9LU=,tag:GzMZwXwIChvafFt8OAhRNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
