apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: home
    labels:
        cnpg.io/reload: "true"
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:cPVgS7lvVKuF2QFahZI=,iv:2OM3yIx2GVyh2Sdwb2HfrlMni2Po48SJvX5/sw/uOzQ=,tag:wMs8pVA7f5gnXB4IPjBUmQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4SKmXXPE4Ae3eGK0XGKAEEbQAmben9XPpa6MM/M5Vfp2Bn0xSklQkhpSVzdM,iv:3RscMe08wsG6zSaC/C5Hca7aksU7x7YdpAGlhmbxaBQ=,tag:l5dfkvDUXynEXmX96kQXdg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:NdeYMg==,iv:Hkitl0EpW0VDhHPfZ79RaUE9rDa7j5VgcJ25h9E39Qo=,tag:lCQ2ekD0UatkAxuxUlcjcQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:jmB9SDHsvay/RGO3L5IS7iSeZcZFzbFmZ/e55Wiv8Fval7Dq,iv:tlwWopkgTjxY92PeW7zzdhkW2AgihAdzG30Pw09mD7I=,tag:xB3rdJ+At8bGCZL5HQGGCQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:NkP8LBbajRQiPJxzwrxwSqH6,iv:aOCJutajxUiv7WyL5roh2AKsyMvE2XRMLBvryKe7x/o=,tag:IFRBZzCUC0W3hsEXm0KAnA==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:pgufVNf3lqeX+8rsl4tsIa9Wa7ekK7k7NaSBnWoITIQGRVjVnWed/pBI7jbzXnkhLeqFRcYHt2NaLmp2H+QikSKNmZ5aGjq+rr2wOqDHgrVzz/MFf3dJNoatwZF1Iz3Xlva7lkOADtDOe6u+87rRHHvkXw==,iv:BCPmknbGpAMtfyf6+xmRqqPQpUtIZjPX5cWWTaoRQmk=,tag:U8kSjF6//ANmIPqxpz0neg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T14:39:02Z"
    mac: ENC[AES256_GCM,data:d/rN+IdPbZ7XPyRqx6mwbWd6hT8UyrPIW58LiLPh5bbL8WxBKSfT/ZV+wbrWGngisASE20cXsTpQXscikKp2L+bf26NFaVRfq1+Ed1msfwgqhLXMUJkfGLAna2CRyMnZGuU/IkTL0osqV5PKT2Fn7PPY6qP0AOB1FJzKmzLyGrs=,iv:qNd/2jZ504BozWX3jTyBqLMCvPeDmXY/Wb++qfmzthw=,tag:FPMhaHytMH3s9347OG+SYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
