apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-db-secret
    labels:
        cnpg.io/reload: "true"
stringData:
    name: ENC[AES256_GCM,data:jEwRBjQ4Vu4QEA==,iv:wnUjFh392BB1ARkD3pFoSS+rgeyVC0iUwn5IWY1o+/A=,tag:4Q/Mfzd5XZwlqXnfu8vxvQ==,type:str]
    user: ENC[AES256_GCM,data:9beVltIK/bHIPQ==,iv:Dn1xumU2JICxC4XER1kQDQR6ocWbxVB4vOctNsoe8Lk=,tag:LL8lmyPESY6M5C92A4ft0g==,type:str]
    password: ENC[AES256_GCM,data:mziYYpV3EV6sTdhdlK6aCZQJImJMSOGiHOQ2trDZUNq3fkkJ,iv:vcLEDKQQQJLxP5cwt3tPdY1jskFIagA5+qw1yeeADdg=,tag:TjPRnpEtNIje9YRbuA5dvA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:xrdgFmX4UUVYqQ==,iv:/RjRTOsmkwlU/UQ9QsJLhMRmAxJEL4xdcX6xnMoeDq4=,tag:2M08qf+/Up8jtKHk9ILE4g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:71ZS+9ghKnVIQA==,iv:N7Ynft0+QMI8GvaB9Y5pLIDAsdETBOAmzYUUGpLat/s=,tag:vf7IydMAD2N0hgMMvkNHmQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:xKv5ELf2R0jgV1+IlcVmy4fdaAYI+07wz7rUrXLR4istqHFH,iv:yarNC/HaOdUV4bfFGVzDIEQsWKET6CIwEb0Egyn42EA=,tag:2iJSjY1WUGtpAzd70GGh/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T06:48:10Z"
    mac: ENC[AES256_GCM,data:t+xTgJjfH121OzSLdEyR0j1xI10Oc1c4yNheHOYXaoSR4Z/EMagsO41dZeb7Ed32ghg5avNAgBgplkkzJSS7ISJYEQ12SnbT33aNP3gNVoLuxzeKoS8Or0gBC77VmbO1jOIFXYBE8BFd5UPNfM7fgjcptnT18lSaZh9kJoxmUhQ=,iv:+b1qHnlo6Xevdbfotig1tLHO56PiQJEtXm5WdVHRH40=,tag:xr+Rzhgp7L4usnf+vkkqXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
