apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
stringData:
    access_token: ENC[AES256_GCM,data:cFpW0Bc3pFmYF0h/7HQ9nGZ2VIUMu+DOCbef8Ir63cdJaGRYTtZjsfyf0BCbWu8NuXGw5X2c6r9zZpm7BfKfTRvVrK5mTqEcl8nm5xT27tOOccCsaT1LK2TckWp7TQajJ9u/Jipj3/NIvcDnZj7kEgkjAj2UQd9dFD5JLb5WWqh5M6GkT8SsntyKfHllXfSXhYwMLZPeFDoTsIdKbfckYh7XZbDcGv4ALdiGBwAQCltMJp6NQygh,iv:hMJtnDE3tuAG2J5468kShHHwKMCJXX0O7DQM2r6CImE=,tag:fUONYiu/+z1hAaxSlcP4Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T02:10:25Z"
    mac: ENC[AES256_GCM,data:ULstoQijwFc0oH/DAFwojRxvOET+bEmCLBHFr14BcXWfH7wjUK1ERVDTJSHOHU/3AyBJdtJzAZyNdX+xivn5x2hin76Ag+Sahfu1KyRzd05HnNzDevAOLvx1bJeGzWUixssl4jjo7Hyv2L1q/sQBLRyL+iNZ9mS+/m0AIbVE1Kg=,iv:+p/gTqR3GR7IShp3525z841e1wfUl4iWZ7UZXKPmV6Q=,tag:ocl+xlW5MNANO9TqZLiGpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
