apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-db-secret
    namespace: home
    labels:
        cnpg.io/reload: "true"
stringData:
    name: ENC[AES256_GCM,data:PU1yiXZ6szbCPWpQvWk=,iv:KhG4r6km7+ysrFBuYkLuKsmEyoKXHFq2bcXKaPr0ZHE=,tag:J9wDw1Ld12TyHAGOFUSP1Q==,type:str]
    user: ENC[AES256_GCM,data:WAyrnw==,iv:lh6kqHf26icSNnpXD+b6VMq4nyRjOjMxx9ZjMWRaJA0=,tag:aOjps3f17lbz61XwmXt9Bg==,type:str]
    password: ENC[AES256_GCM,data:mziYYpV3EV6sTdhdlK6aCZQJImJMSOGiHOQ2trDZUNq3fkkJ,iv:vcLEDKQQQJLxP5cwt3tPdY1jskFIagA5+qw1yeeADdg=,tag:TjPRnpEtNIje9YRbuA5dvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T15:09:54Z"
    mac: ENC[AES256_GCM,data:VRd4AMGEp0QRC+Eh2alQ8E1Sw95BSETyjhpxUHUwhzJ3a2ByslYTenBPXFsdC/pAFFow+DNZ8S7zcDAwY5ji4jrDY0+GOkBg/SdPXqAKFlXGYk/OudWhuI3xTpk+8DM22DO6xKYgQfz15Kl/s7rJrEPI+HQF5+VrYKcnXAn0z38=,iv:lm/ukMtDfJOc5kJVPgGpMnZyG5gWy70z4s13ySFIpSQ=,tag:Yjoo6RkdNz6+dcAAvzdIeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
