apiVersion: v1
kind: Secret
metadata:
    name: ${APP}
    namespace: ${NS}
stringData:
    #ENC[AES256_GCM,data:Xs7EKA==,iv:MPIDb1KT3HmI/Z0EXOPjWEyqsFxklwOmWsdV6ruVrVA=,tag:hPK6b+svOlK7sWuzU7so3A==,type:comment]
    #ENC[AES256_GCM,data:UsX/QEAM8bPFai95K5+f85s0J0adNxTngowpJF3T6rYcYEdU+NPgNI6rsRclUWeI,iv:f6qwnHcSI1fUo6ngHW1D96rImy1H9ycClT5mvHApsT4=,tag:hLuMicUySQ7FMTf9m+MryQ==,type:comment]
    #ENC[AES256_GCM,data:a6qMb6dYoYTiZ7S6noVFebYOhnYFQlc9veUq4CuUr8CGe4kDck8Anx7nM+npNw==,iv:SAW2mZOk+Kg+xzi8poQ//ol9B7jRtSgQKI8mM7MG9qQ=,tag:LDo+KuGLtUQVDsrtVEAQmw==,type:comment]
    #ENC[AES256_GCM,data:T5VelB7GNbCt/xQkoUQ=,iv:N2KM759JY8KA6I+qcGgl7NvUfrthUWrOuJDE/ToUycQ=,tag:RdWlqgLpoCB66nyZDSDmrQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:UTJZbeoWg09fNg==,iv:B1gerAOhPf0QjfI7rNh7N9fr/GBxWes/RYl7mspmtBM=,tag:CY4u4rVnK4+iI70DRG1tnA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:XoaYQOyIe54yYw==,iv:b1K+3B/22auTRBzyBrZmDCbnRVXF4cwROMnmB4t9WnY=,tag:NSPArVuHkkhAYK3w5wuJlQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:kfoZegGqWvJimYlVV3P+rrnawkM=,iv:9CTj2WevlqOXtes6LiuYrgS1tbEpTjXHp9UBcT+zHeY=,tag:BnX6eVVago8GRIwyj0M/2g==,type:str]
    #ENC[AES256_GCM,data:Xs7EKA==,iv:MPIDb1KT3HmI/Z0EXOPjWEyqsFxklwOmWsdV6ruVrVA=,tag:hPK6b+svOlK7sWuzU7so3A==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:dbB/sPRAvvd2Nn207pv3xujNURa0EvXDCR941A9hbyasf6C8BplEImpkP5WgYNNnhV/09DLgIENu+6bCsIZvP/cscxQd/pXAMdD8pM+uoBpfDrOzP2uLlTP4+UFRh8aAkd0NoZWXAV4+,iv:Ru/Ersaaz7CbPe8QsinZJy6Ena94JXd6MPpUN4unbqo=,tag:OhwdNpxworX3AY08jZd28w==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:+iG0VbjPATVUsIUDPEBN9u324e4=,iv:+E6gqx10TvENK3LvANCCnqE6NLMJ5M6ncsqRYfvAZxc=,tag:76QEtIfcyEbCCwsVYEexrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T05:46:40Z"
    mac: ENC[AES256_GCM,data:mNrzQIjWrjeRcPD5PQ+Ikbz7kDvuVvZumNkDkZdShcHgxaFcS4uCTU5Xtj2H/aR8sIka4oSDK/2BRL3N730+fSSWwI7StbBWfCaJwSCr7VzlCfSEsymHnoIk7n276liGtHmzWbPXlt9tOfmHn6LvohQmdkjBZ0j3n7JJXB1Fp40=,iv:hc9QyCLxWZnqXgUOSiXPRitN69KhSz6kz/6ZO+qPoHE=,tag:XSjxxWjBlp9FQS81QFRUuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
