---
apiVersion: v1
kind: Secret
metadata:
  name: "${APP}-volsync-secret"
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: "/repository/${APP}"
  # The repository encryption key
  RESTIC_PASSWORD: ${RESTIC_PASSWORD}
  # ENV vars specific to the chosen back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  # AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  # AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
