---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-fs-app-rep3
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  fsName: ceph-fs-main
  pool: app-data-hdd-rep3
  clusterID: rook-ceph # namespace:cluster
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4 # Filesystem for the PV
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: "Immediate"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-fs-media-ec21
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  fsName: ceph-fs-main
  pool: media-data-hdd-ec21
  clusterID: rook-ceph # namespace:cluster
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4 # Filesystem for the PV
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: "Immediate"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-fs-db-rep3
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  fsName: ceph-fs-main
  pool: db-data-hdd-rep3
  clusterID: rook-ceph # namespace:cluster
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4 # Filesystem for the PV
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: "Immediate"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-fs-db-ec21
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  fsName: ceph-fs-main
  pool: db-data-hdd-ec21
  clusterID: rook-ceph # namespace:cluster
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
  csi.storage.k8s.io/fstype: ext4 # Filesystem for the PV
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: "Immediate"
