---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/kustomize.toolkit.fluxcd.io/kustomization_v1beta1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-monitoring
  namespace: flux-system
spec:
  path: ./kubernetes/apps/flux-system/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  # wait: true
  postBuild:
    substituteFrom: []
  decryption:
    provider: sops
  interval: 15m
  retryInterval: 1m
  timeout: 5m
  dependsOn: []
