---
# CephFS for applications
apiVersion: ceph.rook.io/v1
kind: CephFileSystem
metadata:
  name: ceph-fs-apps
  namespace: &ns rook-ceph
spec:
  metadataPool:
    name: cephfs-meta-rep3
  dataPools:
    - name: app-data-hdd-rep3
  metadataServer:
    activeCount: 1
    activeStandby: true
    resources: # Keep your MDS resources
      requests: { cpu: "35m", memory: "64M" }
    placement: # Keep your MDS placement constraints
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector: { matchExpressions: [{ key: app, operator: In, values: [rook-ceph-mds] }] }
            topologyKey: kubernetes.io/hostname
  storageClass:
    enabled: true
    isDefault: false
    name: ceph-fs-apps # SC for general CephFS use
    # Pool parameter points to the data pool to use for PVs created with this SC
    pool: app-data-hdd-rep3 # Point to your main EC data pool
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    parameters: # Standard CephFS CSI parameters
      csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
      csi.storage.k8s.io/provisioner-secret-namespace: *ns
      csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
      csi.storage.k8s.io/controller-expand-secret-namespace: *ns
      csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
      csi.storage.k8s.io/node-stage-secret-namespace: *ns
      csi.storage.k8s.io/fstype: ext4 # Filesystem for the PV
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-fs-apps
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  fsName: ceph-fs-apps
  pool: app-data-hdd-rep3
  clusterID: &ns rook-ceph # namespace:cluster
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: *ns
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: *ns
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: *ns
  csi.storage.k8s.io/fstype: ext4 # Filesystem for the PV
reclaimPolicy: Delete
allowVolumeExpansion: "true"
volumeBindingMode: "Immediate"
