---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - builtin.yaml
  - block-pools.yaml
  - fs.yaml
  - object-pools.yaml
