apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    GRAFANA_PASS: ENC[AES256_GCM,data:HLnQ4554nwTLFSdnAoyIAclnhKrUthte5JVNZ1WFe30pOZzf,iv:9Z0DPFnInrMG89PE+y0bdam9V5SFjqcflASA0tuS9S4=,tag:62bcWzE7px0sn+eeTjunWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-19T20:40:16Z"
    mac: ENC[AES256_GCM,data:2GCEbpdtnO0BsqOTwDQUKL5XUwa+357MuRWwx+qoJ4IVMTkDp9qncIOX6Qh/SAh1W2rKuxAq49ZvMhAuTzIYgZVW5YGEbiKizzpaJ5Gl3RBvLU8yOD9E0RIXGsXuXd3+e5zD+4K/zTYZh8yCPZ1l3ATQkXuzg5De/++xRIFzoqY=,iv:Z4GglW1NW6kkX/LKPWj+dXvAKpvQefPyeplMe7WB4YY=,tag:ihu8vN8ZZzxHUDHtiU8z+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
