# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: cloudflare
    env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: &secret external-dns-secret
          key: api-token
    extraArgs:
    - --ingress-class=external
    - --cloudflare-proxied
    - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
    - --crd-source-kind=DNSEndpoint
    - --cloudflare-dns-records-per-page=1000
    # - --events
    # - --ignore-ingress-tls-spec
    policy: sync
    sources: ["crd", "ingress"]
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters:
    - "${PUBLIC_DOMAIN}"
    - "${SECRET_DOMAIN}"
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
