apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:V2s6kI2eIGT525YCZUPraJPOlIUcnADYVwbbgJyoTGt85YeP2CDUnA==,iv:3fZhWbNhTOzKkbwBKcGhovO0/5YROMGPZctc9dlfwQc=,tag:vLuVr2i5KGfkkLToNNF9gQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaUxyWHZOZUNyWXdCdTNJ
            WWliQ0VxWUpUU1o3WEppV3B4eXVrV3JsaDFjCldSWkNyQ3lNQkZyeTRxQmFzVVRl
            TVo3REZZTDZQbzZDSFZjY1BKSjRqeDAKLS0tIHlWeE5saHFZSnQ1cElVbTVKbjhC
            R1lOQ2xkUDRtQVVEY05RUzJCR2Y4N2cK9vB0IcsMrIk+bpCUqdtmKwVGkrcDgIen
            ip7im4k9vOlH2mR/xSlte7ZP762DJ+WG5TrpaxhrHUdOudpA7dxbBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T13:15:03Z"
    mac: ENC[AES256_GCM,data:k1u9CMNJuCzqCSdtSI+ui6/YCcyTnaqviSt0wqnstAcN1/Q6X9j3sSygRPb/XGV17LQzddcu1P8HoDJk16W2yPXbpXTwfVPfY/1xb0Vd6weQcsIia2UHxqFCwXrwuRM7fSWhfosuIPN53QT7jiG5bdPchNfm2QlYfNW35RmEo5w=,iv:hVLejha31eWVqC3FaAGVMwewpUwpDmd3488lCOLpb1Y=,tag:0tMX7SDrODOH2UCbzIdVpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
