apiVersion: v1
kind: Secret
metadata:
    name: cnpg-pg-main-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:DPNB+CcZpDZKGWk1m8ddWGfA,iv:Vu/NGa/7gEOW6RuOU+INJ3mQOl6Q8kE0JTrmGs6hpCo=,tag:G9E5lVQmT8GdU52CFh4N5w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:BlMWRMvdVZY3Gf/tRAaneZyckn0OchNXwSWQtWn4hMjGWCDqNg==,iv:YhLogrxkDYGxdyyMSLZxBjq11NsMgXVMACEt3wuOLKs=,tag:xheoKb6D3UH4xVsvFU0EnQ==,type:str]
    INIT_POSTGRES_PORT: ENC[AES256_GCM,data:Ugf22g==,iv:f20Z85W9hDIK+nihf0eA9uIodmAw5i9U1uzJWP6Rn94=,tag:pZ5woubxScuC8X2/6VK8ZA==,type:str]
    INIT_POSTGRES_RW: ENC[AES256_GCM,data:h+mWBj6AA26m1RMOC0CV0A1Ap5DWHpimQMvNnTgQjXYDT8pOTw1/Wt5F,iv:7M3trXToJGGOv/12lP6tNyyCD+Up5kHmUwUbWUr9HWc=,tag:zlPnhM4xR4rSMn3eGc3pzQ==,type:str]
    INIT_POSTGRES_RO: ENC[AES256_GCM,data:mUZvYpzKg3Ley8JQ6SrCNyqt84cJCz/3uBr3xK0t1p7Dr0SILmmbXmSN,iv:/WKQhbN85+Z999/f7Wo+RXCkDrrYe6AMFDLm39O7+D4=,tag:bog3lEH3yxT/yWj1aL5xxw==,type:str]
    host: ENC[AES256_GCM,data:sdJY6/TNIkQA/1zD8vUlrn38Pj8SEAdR337pDQwBCZMkXCOq6g==,iv:N0UbehHfU6PUkhleMrJ61i5IVeYiNOnEfV4SOBuv59o=,tag:oDLbBkB7eXGt+rhFgEgo4A==,type:str]
    port: ENC[AES256_GCM,data:KirkDA==,iv:pa95QP48p+IK3pSGl4O1OrqhnPt8VWXG9pEEQxfqjWM=,tag:r0mrgWF9uESRvPZCs4UVVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-22T05:03:12Z"
    mac: ENC[AES256_GCM,data:BK15xeVF0IiQTEug8BNXLleJ5tPReSQob811CfUuYyhnySYqmEKH2FVCU93ZH1BPCxNZBCCWxJ0/ZFH8jWwIhuPBkXkPxivKBWGrzm0oIjy985UDQGeWCzGevVx+VkWojEV1ktQOZZtHVJa7s1fDjm/V+DvucZECWQHsHVVwsJE=,iv:5Dz9qXcxROKuFvtE90LjJAQGbnEedc0HMQ5aFS0dbFM=,tag:dkm8mrwCKJYf4+xgYj8Fvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
