---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage
  namespace: storage
data:
  hl-zfs-pv-slow: mainV1P2/.k8s/pv
  hl-zfs-pv-slow-private: mainV1P2/.k8s/pv-private
  cloudnative-pg: mainV1P2/.k8s/pg
