apiVersion: v1
kind: Secret
metadata:
    name: main16-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: home,monitoring,dev
stringData:
    username: ENC[AES256_GCM,data:IIPAH/Fr,iv:aEoNyMJgOGGQ0tE5168ytD4z187bkOlgkJo28hoXu/U=,tag:6flUndMXOFG0xpzgu+u9IQ==,type:str]
    password: ENC[AES256_GCM,data:UPcsFD4AK3jRK1Rvq+MR+uTK,iv:lHLnnqj3nq5U4bRKDpkx5YfQU68HvoKQ45TTY9Qgbak=,tag:r8/+e0Qt3X3CphGZZT/0pg==,type:str]
    host: ENC[AES256_GCM,data:LSdvk6vqnPJkT+zcuq2TZCmA2qRqc+QWfya0v6+P1Nolz+Iq/AZvV+Ft7a9d,iv:+r30BB5a/pLZtkfbVxnG5oRle80r8MLpoMdIXaLRSXw=,tag:vOtq2/k2u9klh+vOo7hocQ==,type:str]
    port: ENC[AES256_GCM,data:KirkDA==,iv:pa95QP48p+IK3pSGl4O1OrqhnPt8VWXG9pEEQxfqjWM=,tag:r0mrgWF9uESRvPZCs4UVVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-24T13:37:52Z"
    mac: ENC[AES256_GCM,data:4xM+lDdgDHRPJGgNi1oEVCs7JznO1mmFk13j2fvk9+//zNS6+ZTNy5eyFXtMOgeaYsaeXzAL5VvLadk1dtusSdv9HDYKjbXy7YMwcKI81w9W4HstfPOIhAuBYBEZCES8c5IYME12bl+tXxvU7d4hmgaxPfmbIklCf/Mld0CQSWg=,iv:h1EXhmLjAOX40FeckoeKWMVW1FfJSSCckClw4Ps1Ik8=,tag:aQbAeRWmMdtSSbYlR/uExA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
