apiVersion: v1
kind: Secret
metadata:
    name: main16-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    username: ENC[AES256_GCM,data:IIPAH/Fr,iv:aEoNyMJgOGGQ0tE5168ytD4z187bkOlgkJo28hoXu/U=,tag:6flUndMXOFG0xpzgu+u9IQ==,type:str]
    password: ENC[AES256_GCM,data:UPcsFD4AK3jRK1Rvq+MR+uTK,iv:lHLnnqj3nq5U4bRKDpkx5YfQU68HvoKQ45TTY9Qgbak=,tag:r8/+e0Qt3X3CphGZZT/0pg==,type:str]
    host: ENC[AES256_GCM,data:LSdvk6vqnPJkT+zcuq2TZCmA2qRqc+QWfya0v6+P1Nolz+Iq/AZvV+Ft7a9d,iv:+r30BB5a/pLZtkfbVxnG5oRle80r8MLpoMdIXaLRSXw=,tag:vOtq2/k2u9klh+vOo7hocQ==,type:str]
    port: ENC[AES256_GCM,data:KirkDA==,iv:pa95QP48p+IK3pSGl4O1OrqhnPt8VWXG9pEEQxfqjWM=,tag:r0mrgWF9uESRvPZCs4UVVw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:gaD8JZ/tmzYX6u8a75D5I3QTyVEMBvjoRMxUgVd419r67X3HTB2Z5HyXs0FY,iv:sG5llUO4tj75Z7g+q18jLCOCFD4ZKdXzezhkzv3k42s=,tag:96m4tXptkketa474y9BmXQ==,type:str]
    INIT_POSTGRES_PORT: ENC[AES256_GCM,data:xpVDBw==,iv:7FPUvK9u9OBALPCUwiqCqqd8O6LVqhM5hiaZ6zo2eJM=,tag:xgKrwiG5AWUMAaD467kdhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T14:42:19Z"
    mac: ENC[AES256_GCM,data:cqvofBnd+INbo1L3AGh65EDGL4E5FUHNfj4Xxx4sn7kgQDJliMtuOr9Rk3FkTYwVtL4fjUTjVDkHSym2u7P1SWo4Z2ZhSri4wOgjSZWDfoKoGz2bUAfUkVy22vrFnYFI3b1+rEJUmKJvEGB3bwU5XxA5WLGr2Wf278P6Bp8Anvk=,iv:209PxeUset6XEdOhHYeXtLe3hrqGBIXnjMtv7BGVJ2M=,tag:CLLIYTebGGUEK7CCbe+JtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
