---
apiVersion: v1
kind: Service
metadata:
  name: postgres-main-lb
  annotations:
    io.cilium/lb-ipam-ips: 192.168.4.11
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres16-main
    role: primary
