---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-nuclio
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/development/nuclio/app
  targetNamespace: &ns dev-nuclio

  commonMetadata:
    labels:
      app.kubernetes.io/name: &app nuclio
      app.kubernetes.io/group: dev

  postBuild:
    substitute:
      APP: *app
      NS: *ns

  interval: 1h
  prune: true
  retryInterval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn: []
