---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hr.yaml
  - object-bucket-claim.yaml
configMapGenerator:
  - name: loki-alerting-rules
    files:
      - loki-alerting-rules.yaml=./resources/loki-alerting-rules.yaml
generatorOptions:
  disableNameSuffixHash: true
