apiVersion: v1
kind: Secret
metadata:
    name: harbor-regcred
    namespace: dev
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: media,dev,home
data:
    .dockerconfigjson: ENC[AES256_GCM,data:w6CJavAvcbc7Bg2vFCCL0x9YsXFh/FmwpVmGUPxuSS2De4a2DeT1Vm6dbAmjyNQU5zvpOzKQbxnhmo0BuQTEePHoX98u2m6AHE3JqkHZlKuw8UAkLDZWu2M5FTKU2Is8wA1ej4tjci5vxtDutDdkRGJqduS1hPAvlYS48lkMREErLSeam67DA19auLtNdMyOdhKS7DbOyNJboOceSjsk0WiL8ykcmd8ZfgCRg7SQuVfXwuD+a+fvc6haWbKquNX9qTsadaWVSdZsjYo/SRl/JxZz/Qxf3Irhl7QHdFGUznWQPHi51CHnNbQjEL5EUWap88Zoq/Q3Q5B//pyCE+T0a6eOee/o9VwQtgS9Al7PEF9dAVQUdvQ/ihNmf6nbw2Rf+adXy8jU7S1LQPSA2PbL8kLeZZIvt0a/brs3NZ08sT0mKMG8JFVwBbp/LJQdmoMi0srZ/D+bLpFHFSGqES9XL+wZ731ofPTBk4IMcrmqygNm0PsO,iv:M4GDfAXMeP0LgG5cmRWQIXZWwJDJWe70xEnz1nyfTpo=,tag:zx5/eyJ+yn3XiMSHej3H8w==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T03:27:48Z"
    mac: ENC[AES256_GCM,data:weTgL8EO3OD5rU9fjsiTw/h3OianvjRTr71CLtu8aF29q1z33x44RYjJDR7XXG9QVXbS4LHdTtP7c8+8xJch9VpXp8qobrc7aRuT9xl8YXhChcqzL9UKkgF3qe7NtuWQHk6zGDI+0G3Mxss9+aQy8j9sMsbOPWyns8ZlReF9Ico=,iv:hCdzAvg1esPyPLET6ywGW+emu9Qpl7pPIJEdNyqVfbs=,tag:DZ0rvhJkXyKK+ZNJubsq1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
