apiVersion: v1
kind: Secret
metadata:
    name: harbor-secrets
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: media
stringData:
    secretKey: ENC[AES256_GCM,data:c1g7gLem+8kwAKtKl7K6Ul6ArMpozl23,iv:7bv/KbDXMXWubU80zqifTbuppkSJEcCiqZb8G7KjgnA=,tag:l/CjbEoEoBfeeW9lU77dWw==,type:str]
    harborAdminPassword: ENC[AES256_GCM,data:h2aXIdLeYA==,iv:tYJxjXfcMqlcN9de6upmgJ7j+utAiqpFM610N7wwKGY=,tag:i8ktstoBWRqwAo82vwSzfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T01:20:13Z"
    mac: ENC[AES256_GCM,data:x0KicZ5g8Up7cKSuOqEKpTIhJ+7dag5Nr3qMd8be9PRGYJ9L3Oj4fRSYVmxcBAsgFg6wP4oS39HwFqXZmn2CV1u58kkojj/AbMNifPEoxh02PfUjNn+wHsck8eHSwJRvPY6iu7TRyyIPbl2jhUA2SdR1zcIU3bFPZCnTGdc9bk4=,iv:kaAvtSkTC0e0pyCsdtq/gzFzAz9PMpDvB9CpKLRNCCw=,tag:eLSh2/ABQxaGGkVw/xtJ2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
