apiVersion: v1
kind: Secret
metadata:
    name: harbor-db-secrets
    namespace: dev
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: media
stringData:
    #ENC[AES256_GCM,data:HO5IMbJLwwoF,iv:OXTwcut7f3go7pE1jsuD0exetcno5KK006ea17szzJk=,tag:FaLtBQZoh0FyoRj1WGj2Iw==,type:comment]
    user: ENC[AES256_GCM,data:/m9lUxQJ,iv:JfOwAUObwgAbqYXwf2Q+1GTygvaA8sLUNBt6DBMwypY=,tag:maPlfCAL5ZPnrEpCl3hMPw==,type:str]
    name: ENC[AES256_GCM,data:LHOQVGFT,iv:QDWfQCORhO5EMILaQ4vt7ZnHu62VXSJSpBCZPAoI1IQ=,tag:Z1Z8FoR/jo6pPeqZQFz3gg==,type:str]
    #ENC[AES256_GCM,data:zlOT5kuq7ma9cG5snAmo0Uv1,iv:vQXeUTALQpVYigcF+NJhPV/gQdMk6rHcJj0c5V4OEuk=,tag:+igZP2YauR/iacy/q41l9A==,type:comment]
    password: ENC[AES256_GCM,data:DB+K+9UcYnMkIr/gA8NflZtvVEfPe7cw,iv:DWAgOIZLXQhUPQVXLVKOEfaMW+knMhOicnU3xMLmhBU=,tag:8rZGoWOnIWLMYpDbXaHgEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-24T13:05:16Z"
    mac: ENC[AES256_GCM,data:tGr7MqYbBlw/YK+yg72j+NOkUBSIRAb5p0K+GZPTc56eks/4aPXSsPn5ANYix31XQAeIal/SNdI1N17+TySkVMoAslOwCbd8NFoMaw1jAR9/D2ZbY1jYQQT1cPC34AjcKIGRy9W5ptl/CMiEq82xOgweyH15J0vQX0YksMFsuzg=,iv:WXNTrbmjKqtHyYPOs+x1S/Cei/h+GQTcP4EOpd9f/Oc=,tag:QNyk8yWcIxTV0XUWxvdyeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
