apiVersion: v1
kind: Secret
metadata:
    name: harbor-regcred
    namespace: dev
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: media,dev
data:
    .dockerconfigjson: ENC[AES256_GCM,data:hPskFiHE1+Zk57tteRoHzmhhSqVmP4Z+DiJIXQSuzkWaKUvVAlbOcDsiwvDQZceNfBYYCtIzxYxfgW3nxb0X+EqKz7D04M2vJPx8QUNZ6eauRO2Qa4SnrF0ybMWdu+4xvVXn+ivEHK4Lnj+duT/p/wIalBQ8iISaPqW1+7G5xjRjLfVYyxIMnVrwSR7o09cD9bXc9ria1s3bX4yOuds6AUC/V33JikL1HgjDC8GVK2BbbnguMQd0+G15ePogR3NP3mLwpDX/jVR/Opwk7/so3AT1vW7eIyK0jIeUos31cJYPvgQqLDB/5Nq87stFhGapeoXjGJGhcKR+QICuqjfnHPhHw1giC5Up+4lO1fdRrHMZjx7jgI9SkL51ZRAqBv/sIiUWSev84t9fueMYRHoP5v/5mdnzZV2qL1jdRWuSAUED382Nh5BShJW6Me4ZzIyV8VCFtD1LTZbbIsHl2i8wH+DjFYaDwmsBOd6XGPwT5xdrtb7ZAN0SaUgKp+J03Emvq/74wbIO5hnek+egpa7iNzfQAqdhRa5Q6k1mR5KNju2MsCzdeH6zoL1mqUeo0dvs7NIv/DiKsJcON70A0M7KWrVVZcQm08rVARkFH6LXJ14TjGjB2uCjEcGE9Bb+GMRwUCZwTFcGM0q54pviDIpJiYxd7/zJnU0rA53hfXB77i5jtZqTgsueLcIX6GcuqJ1mjy7BOr/NUSSaai4sY2M/ZzFvYwy8xL9voolMZG9hNHmNmWgVFYAqPHx/8irJFzdTapbJhJFj7Eluxn5s8HJowQhve0fYh+p9/xqg,iv:lvT9y1+dAPQNb61Z37x5IGQhn+xn24v+dmqm0ae3CQE=,tag:adeNig6VvRRXxxRGFc757A==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-24T15:32:39Z"
    mac: ENC[AES256_GCM,data:mg4awYjdYlwkjYPGzPBcKYr1TZzLx+MBLtbzT5SUGR3P+MP/5gjg49hojDwz7gMRzXiPu7r4nk6qI1HBgTrqhDl6/XPTkGhDtjMjXHpvO2VHzzXsqB4r4ULVcWlDb4Yl4PMWdEdDWPVdd/H29LGzadTWFnUPsEmsAI9gLVArSBQ=,iv:8hwoP96JHBEI3D8o7/S9TPls/y0JGiYV++ntqpg/LKo=,tag:PNFfVQyoglJ6+tGkiN6i6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
