---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name cluster-monitoring
  namespace: flux-system
spec:
  namePrefix: "monitoring-"
  dependsOn:
    - name: cluster-config
    - name: cluster-storage
  interval: 30m
  path: ./kubernetes/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: cluster-settings-user
        optional: true
      - kind: Secret
        name: cluster-secrets-user
        optional: true
  patches:
    # add decryption into fluxcd Kustomization
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          interval: 5m0s
          retryInterval: 1m0s
          timeout: 10m0s
          decryption:
            provider: sops
            secretRef:
              name: sops-age
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization

    # add defaults into fluxcd Kustomization
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          interval: 5m0s
          retryInterval: 1m0s
          timeout: 10m0s
          prune: true
          wait: true
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: kustomization.flux.home.arpa/default in (true)
        # labelSelector: kustomization.flux.home.arpa/default notin (false)

    # kustomization.flux.home.arpa/default: "true"
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          sourceRef:
            kind: GitRepository
            name: home-kubernetes
          interval: 5m0s
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: kustomization.flux.home.arpa/default in (true)
        # labelSelector: kustomization.flux.home.arpa/default notin (false)

    # substitution.flux.home.arpa/disabled: "false"
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-settings
              - kind: Secret
                name: cluster-secrets
              - kind: ConfigMap
                name: cluster-config-versions
                optional: false
              - kind: ConfigMap
                name: cluster-settings-user
                optional: true
              - kind: Secret
                name: cluster-secrets-user
                optional: true
      target:
        group: kustomize.toolkit.fluxcd.io
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)

    # dependsOn: cluster
    - patch: |
        - op: add
          path: /spec/dependsOn/0
          value:
            name: cluster
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: kustomization.flux.home.arpa/default in (true)
        # labelSelector: kustomization.flux.home.arpa/default notin (false)

    # prune.flux.home.arpa/disabled: "true"
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          prune: false
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: prune.flux.home.arpa/disabled in (true)
        # labelSelector: prune.flux.home.arpa/disabled notin (true)

    # wait.flux.home.arpa/disabled: "true" => wait: false
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          wait: false
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: wait.flux.home.arpa/disabled in (true)
        # labelSelector: wait.flux.home.arpa/disabled notin (true)

    # kustomization.flux.home.arpa/helmpatches != "false"
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          patches:
          # add decryption into fluxcd Kustomization
          - patch: |-
              apiVersion: kustomize.toolkit.fluxcd.io/v1
              kind: Kustomization
              metadata:
                name: not-used
              spec:
                interval: 5m0s
                retryInterval: 1m0s
                timeout: 10m0s
                decryption:
                  provider: sops
                  secretRef:
                    name: sops-age
            target:
              group: kustomize.toolkit.fluxcd.io
              version: v1
              kind: Kustomization

          # add defaults into fluxcd Kustomization
          - patch: |-
              apiVersion: kustomize.toolkit.fluxcd.io/v1
              kind: Kustomization
              metadata:
                name: not-used
              spec:
                interval: 5m0s
                retryInterval: 1m0s
                timeout: 10m0s
                prune: true
                wait: true
            target:
              group: kustomize.toolkit.fluxcd.io
              version: v1
              kind: Kustomization
              labelSelector: kustomization.flux.home.arpa/default in (true)
              # labelSelector: kustomization.flux.home.arpa/default notin (false)

          # kustomization.flux.home.arpa/default: "true"
          - patch: |-
              apiVersion: kustomize.toolkit.fluxcd.io/v1
              kind: Kustomization
              metadata:
                name: not-used
              spec:
                sourceRef:
                  kind: GitRepository
                  name: home-kubernetes
                interval: 5m0s
            target:
              group: kustomize.toolkit.fluxcd.io
              version: v1
              kind: Kustomization
              labelSelector: kustomization.flux.home.arpa/default in (true)
              # labelSelector: kustomization.flux.home.arpa/default notin (false)

          # substitution.flux.home.arpa/disabled: "false"
          - patch: |-
              apiVersion: kustomize.toolkit.fluxcd.io/v1
              kind: Kustomization
              metadata:
                name: not-used
              spec:
                postBuild:
                  substituteFrom:
                    - kind: ConfigMap
                      name: cluster-settings
                    - kind: Secret
                      name: cluster-secrets
                    - kind: ConfigMap
                      name: cluster-config-versions
                      optional: false
                    - kind: ConfigMap
                      name: cluster-settings-user
                      optional: true
                    - kind: Secret
                      name: cluster-secrets-user
                      optional: true
            target:
              group: kustomize.toolkit.fluxcd.io
              kind: Kustomization
              labelSelector: substitution.flux.home.arpa/disabled notin (true)

          # dependsOn: cluster
          - patch: |
              - op: add
                path: /spec/dependsOn/0
                value:
                  name: cluster
            target:
              group: kustomize.toolkit.fluxcd.io
              version: v1
              kind: Kustomization
              labelSelector: kustomization.flux.home.arpa/default in (true)
              # labelSelector: kustomization.flux.home.arpa/default notin (false)

          # prune.flux.home.arpa/disabled: "true"
          - patch: |-
              apiVersion: kustomize.toolkit.fluxcd.io/v1
              kind: Kustomization
              metadata:
                name: not-used
              spec:
                prune: false
            target:
              group: kustomize.toolkit.fluxcd.io
              version: v1
              kind: Kustomization
              labelSelector: prune.flux.home.arpa/disabled in (true)
              # labelSelector: prune.flux.home.arpa/disabled notin (true)

          # wait.flux.home.arpa/disabled: "true" => wait: false
          - patch: |-
              apiVersion: kustomize.toolkit.fluxcd.io/v1
              kind: Kustomization
              metadata:
                name: not-used
              spec:
                wait: false
            target:
              group: kustomize.toolkit.fluxcd.io
              version: v1
              kind: Kustomization
              labelSelector: wait.flux.home.arpa/disabled in (true)
              # labelSelector: wait.flux.home.arpa/disabled notin (true)
          - patch: |-
              apiVersion: helm.toolkit.fluxcd.io/v2beta1
              kind: HelmRelease
              metadata:
                name: not-used
              spec:
                interval: 30m
                maxHistory: 5
                install:
                  createNamespace: true
                  remediation:
                    retries: 5
                upgrade:
                  cleanupOnFail: true
                  remediation:
                    retries: 5
                uninstall:
                  keepHistory: false
            target:
              group: helm.toolkit.fluxcd.io
              version: v2beta1
              kind: HelmRelease
              labelSelector: helm.flux.home.arpa/default notin (false)
          - patch: |-
              apiVersion: helm.toolkit.fluxcd.io/v2beta1
              kind: HelmRelease
              metadata:
                name: not-used
              spec:
                chart:
                  spec:
                    chart: app-template
                    version: 3.1.0
                    sourceRef:
                      kind: HelmRepository
                      name: bjw-s
                      namespace: flux-system
            target:
              group: helm.toolkit.fluxcd.io
              version: v2beta1
              kind: HelmRelease
              labelSelector: helm.flux.home.arpa/app-template=true
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: kustomization.flux.home.arpa/helmpatches notin (false)

