---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name cluster-test
  namespace: flux-system
spec:
  namePrefix: "cluster-test-"
  dependsOn:
    - name: cluster-config
  wait: true
  interval: 30m
  path: ./kubernetes/test
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: cluster-settings-user
        optional: true
      - kind: Secret
        name: cluster-secrets-user
        optional: true
  patches:
      - patch: |-
          apiVersion: kustomize.toolkit.fluxcd.io/v1
          kind: Kustomization
          metadata:
            name: not-used
            annotations:
              flux.home.arpa/testtag: newTag
        target:
          group: kustomize.toolkit.fluxcd.io
          version: v1
          kind: Kustomization
          labelSelector: kustomization.flux.home.arpa/default notin (false)
