---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: versions
    namespace: flux-system
    envs:
      - ./versions.env
  - name: node
    namespace: flux-system
    envs:
      - ./node_main.env
generatorOptions:
  disableNameSuffixHash: true
