---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ${APP}
  namespace: ${NS}
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist

    controllers:
      n8n:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.3
              pullPolicy: IfNotPresent
            env:
              - name: INIT_POSTGRES_HOST
                valueFrom: &db_host
                  secretKeyRef:
                    name: main16-secret
                    key: host
              - name: INIT_POSTGRES_SUPER_PASS
                valueFrom:
                  secretKeyRef:
                    name: cloudnative-pg-secret
                    key: password
              - name: INIT_POSTGRES_DBNAME
                valueFrom:
                  secretKeyRef:
                    name: n8n-secrets
                    key: DB_POSTGRESDB_DATABASE
              - name: INIT_POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: n8n-secrets
                    key: DB_POSTGRESDB_USER
              - name: INIT_POSTGRES_PASS
                valueFrom:
                  secretKeyRef:
                    name: n8n-secrets
                    key: DB_POSTGRESDB_PASSWORD
            envFrom: &envFrom
              - secretRef:
                  name: n8n-secrets
        containers:
          n8n:
            image:
              repository: docker.io/n8nio/n8n
              tag: 1.64.0
            env:
              # Isolating N8N
              N8N_DIAGNOSTICS_ENABLED: false
              N8N_VERSION_NOTIFICATIONS_ENABLED: false
              N8N_TEMPLATES_ENABLED: false
              N8N_PERSONALIZATION_ENABLED: false
              EXTERNAL_FRONTEND_HOOKS_URLS: ""
              N8N_DIAGNOSTICS_CONFIG_FRONTEND: ""
              N8N_DIAGNOSTICS_CONFIG_BACKEND: ""

              # URL
              N8N_PORT: &port 5678
              N8N_HOST: &host "n8n.${SECRET_DOMAIN}"
              WEBHOOK_URL: "https://n8n.${SECRET_DOMAIN}"
              # Public API
              N8N_PUBLIC_API_DISABLED: true
              N8N_PUBLIC_API_SWAGGERUI_DISABLED: true

              NODE_FUNCTION_ALLOW_BUILTIN: "*"
              GENERIC_TIMEZONE: ${TIMEZONE}

              N8N_LOG_LEVEL: debug
              N8N_LOG_OUTPUT: console, file

              N8N_DIAGONISTICS_ENABLED: false
              N8N_HIRING_BANNER_ENABLED: false
              N8N_USER_MANAGEMENT_DISABLED: true

              N8N_METRICS: true
              N8N_USER_FOLDER: /home/n8n
              DB_POSTGRESDB_HOST: *db_host
            envFrom: *envFrom

    service:
      n8n:
        controller: n8n
        ports:
          http:
            port: *port

    ingress:
      external:
        annotations:
          hajimari.io/icon: mdi:water-flow
          external-dns.alpha.kubernetes.io/target: ${SECRET_DOMAIN}
        hosts:
          - host: n8n.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: n8n
                  port: *port
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: ${VOLSYNC_CLAIM}
        advancedMounts:
          n8n:
            n8n:
              - path: /home/n8n

    resources:
      requests:
        cpu: 20m
        memory: 128M
