apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: home
stringData:
    DB_TYPE: ENC[AES256_GCM,data:ncl4sWbisNXXRA==,iv:yLvxmtENOJF/WZiYV+ElXhjLhUi18aBTS5V73X2g++A=,tag:PEqga2vJmU7su/UdmEuCtQ==,type:str]
    DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:sK1j,iv:dBoCemvutJStl1l45xESpkIWDNghcF96M9IrMRmcVU0=,tag:gN5b+xn8JO9BSSKRLqaMCg==,type:str]
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:RzQU6sitxv11AV0SgP8zIfGThOk=,iv:e3HlF07auYxhjHxR+q2wv/WnW1SvY/DIBhwNyJ1tWIM=,tag:XLAFo/cJ4F37vc2/Ko/CVg==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:wVVt3HmMifP/6PkpsWRo8efl9Es=,iv:TyYfq8hYKZKm80jzGhXumzxWoiG3qYha5+gP2xjolUU=,tag:bSAwAw9ma+dMUzLD5ERVXg==,type:str]
    DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:0IOI9Q==,iv:oW2Yif6KT/gr/keXGYJ0BHrHkCF4DvAq8sK2/fWJuCA=,tag:8yh5o94zjGoTUKYN2qOIOw==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:OLHoY8Gs7LZeYw5KlyAyJhAn79I36eGktA==,iv:K4t1nSNAf0OD9QtGKxvAEt0r9ASF5nPrTsZ3Gh+j3Xg=,tag:Xhw4qpQb81fD/zMl7AyQuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-23T02:47:57Z"
    mac: ENC[AES256_GCM,data:GMyw406RTEemr42S8EwpBzYBwuHWwmtvOU6QKoonwBDAPLrImPiKe67aP/WhmsZym9QXbEYte+zaADlyZ/lJ6KD6BYcWifFuxwLAsyvSLJsVDU44KN0HYjVTUTlARJhLwYBfPY1keuzkNBhybx2REiqra7g9+CTAGWiHF5/QGsI=,iv:39jQNbAt11Eh8k6yj2syTVrK6iO+NYFtax+HLKteLHY=,tag:uXL+yMQFqyXHhZ8SjXketA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
