---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app prometheus-stack
  namespace: flux-system
  labels: &ll
    kustomization.flux.home.arpa/default: "true"
    kustomization.flux.home.arpa/helmpatches: "true"
    substitution.flux.home.arpa/disabled: "false"
    prune.flux.home.arpa/disabled: "false"
    wait.flux.home.arpa/disabled: "false"
    storage.flux.home.arpa/required: "true"
spec:
  targetNamespace: monitoring
  dependsOn:
    - name: cluster-storage
    - name: network-cert-manager
    - name: system-crds-prometheus-stack
    - name: system-metrics-server
    - name: monitoring-prometheus-rules
    - name: monitoring-thanos
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/monitoring/kps/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 15m
  prune: true
  postBuild:
    substitute:
      APP: *app
      # renovate: datasource=docker depName=quay.io/thanos/thanos
      THANOS_VERSION: v0.38.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-rules
  namespace: flux-system
  labels: &ll
    kustomization.flux.home.arpa/default: "true"
    kustomization.flux.home.arpa/helmpatches: "true"
    substitution.flux.home.arpa/disabled: "false"
    prune.flux.home.arpa/disabled: "false"
    wait.flux.home.arpa/disabled: "false"
spec:
  targetNamespace: monitoring
  path: ./kubernetes/monitoring/kps/rules
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  postBuild:
    substituteFrom: []
  interval: 15m
  retryInterval: 1m
  timeout: 5m
  dependsOn: []
    # - name: monitoring-prometheus-stack-crds
