---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-prometheus-rules
  namespace: flux-system
  labels: &ll
    kustomization.flux.home.arpa/default: "true"
    kustomization.flux.home.arpa/helmpatches: "true"
    substitution.flux.home.arpa/disabled: "false"
    prune.flux.home.arpa/disabled: "false"
    wait.flux.home.arpa/disabled: "false"
spec:
  targetNamespace: monitoring-prometheus-stack
  components:
    - ../../../components/ns

  path: ./kubernetes/monitoring/kps/rules
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  postBuild:
    substituteFrom: []
  interval: 15m
  retryInterval: 1m
  timeout: 5m
  dependsOn: []
    # - name: monitoring-prometheus-stack-crds

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-prometheus-stack
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/monitoring/kps/prometheus
  targetNamespace: &ns monitoring-prometheus-stack
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app prometheus-stack
      app.kubernetes.io/group: monitoring

  dependsOn:
    - name: cluster-storage
    - name: cluster-network
    - name: cluster-system
    - name: monitoring-prometheus-rules
    - name: monitoring-thanos

  postBuild:
    substitute:
      APP: *app
      NS: *ns
      # renovate: datasource=docker depName=quay.io/thanos/thanos
      THANOS_VERSION: v0.39.1

  interval: 1h
  prune: true
  retryInterval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-loki
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/monitoring/kps/loki
  targetNamespace: &ns monitoring-prometheus-stack
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app loki
      app.kubernetes.io/group: monitoring

  postBuild:
    substitute:
      APP: *app
      NS: *ns
      StorageClass: ceph-fs-observability-ec31

  interval: 1h
  prune: true
  retryInterval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-storage

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-thanos
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/monitoring/kps/thanos
  targetNamespace: &ns monitoring-prometheus-stack
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app thanos
      app.kubernetes.io/group: monitoring

  postBuild:
    substitute:
      APP: *app
      NS: *ns
      StorageClass: ceph-fs-observability-ec31

  interval: 1h
  prune: true
  retryInterval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-storage
    - name: monitoring-prometheus-rules
