---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-multus
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/kube-system/multus/app"
  postBuild:
    substituteFrom: []
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn: []
  targetNamespace: &ns kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-multus-config
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/kube-system/multus/config"
  postBuild:
    substituteFrom: []
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: system-multus
  targetNamespace: &ns network
