---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: system-crds-prometheus-operator
spec:
  interval: 15m0s
  chart:
    spec:
      chart: prometheus-operator-crds
      version: "11.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  upgrade:
    force: true
  install:
    crds: CreateReplace
