apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-users
    namespace: ${NS}
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitoring
stringData:
    clickhouse_user_password_plain: ENC[AES256_GCM,data:MhKrvs35J0m8jQ==,iv:X6rQTyC9cs5b/soG+y6ruLkbat+ztZPceOOpmy4nsHc=,tag:LYF4P+iY6f4Z3TGwNgFEEQ==,type:str]
    clickhouse_monitoring_user: ENC[AES256_GCM,data:YZG/1LxwlD3Ybm8u2gBm,iv:mGS1DUO2PmuWvb136ABPt7zPv3k5sWlU9WvGvJSIVX0=,tag:F7Sy17QCQIjgNMLDg3SIkA==,type:str]
    clickhouse_monitoring_password: ENC[AES256_GCM,data:UbXA9+fT8tTA+HE=,iv:yvLn3hySdBFLaUfw8o7pBsxE98zxd6LGPvfKQJCyaBU=,tag:2mVHbg59pKq5VqwVVcxRjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-20T15:11:54Z"
    mac: ENC[AES256_GCM,data:+NgHkixZKfjqitlKOit+gsTyP1b7fjeq2VMEO1ouz3JojpjXhIc1yKzYKfoRUpZ+ivXHT/OndgR3zF6pUgR6XtHq+w3O7O0zzhB9T9IRnrlRk7nzh7rWjNEuorAOlPtyXLtw87cyFrslpptmep+k+qEo73+l+/A4+JMyZLp5MF8=,iv:xb2d4/cC3lAeqRMuAd5boxU2WBKQZKC9rNsQ/Qc01D4=,tag:T6jcbUd9gMq4s9EQ15fMkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
