---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ${APP}
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *app

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    controllers:
      *app :
        type: deployment
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6
            envFrom: &envFrom
              - secretRef:
                  name: &db ${DB_MAIN_SECRET}
              - secretRef:
                  name: &secrets ${DB_SECRET}
              - secretRef:
                  name: &mongo_db mongodb-librechat-secrets

        containers:
          app:
            image:
              repository: ghcr.io/danny-avila/librechat-dev
              tag: latest@sha256:869a40f083408906c607a52d5a58878fff2d6b17e91d1104831d6e8271544055
            envFrom: *envFrom

            env:
              PORT: "3080"
              NODE_ENV: "development"
              # ALLOW_EMAIL_LOGIN: "false"
              ALLOW_SOCIAL_LOGIN: "true"
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1000Mi
            probes: &probes
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: false

          meilisearch:
            image:
              repository: getmeili/meilisearch
              tag: v1.18.0
            envFrom: *envFrom
            env:
              MEILI_NO_ANALYTICS: true
              MEILI_DB_PATH: "/meili_data"
              MEILI_LOG_LEVEL: "debug"
              MEILI_LOGS_MODE: "json"
            probes: *probes

          ragapi:
            image:
              repository: ghcr.io/danny-avila/librechat-rag-api-dev-lite
              tag: latest@sha256:f62a736ae997dc45029e93e785d0a306f4fbd685fece305950c1169e38db0dc7
            envFrom: *envFrom
            env:
              RAG_OPENAI_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *secrets
                    key: LITELLM_API_KEY
              RAG_OPENAI_PROXY:
                valueFrom:
                  secretKeyRef:
                    name: *secrets
                    key: LITELLM_URL
              RAG_USE_FULL_CONTEXT: "true"
              DB_HOST:
                valueFrom:
                  secretKeyRef:
                    name: *db
                    key: INIT_POSTGRES_HOST
              DB_PORT:
                valueFrom:
                  secretKeyRef:
                    name: *db
                    key: INIT_POSTGRES_PORT
              RAG_PORT: &rag_port "8001"

            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            probes: *probes

          exporter:
            dependsOn: app
            image:
              repository: ghcr.io/virtuos/librechat_exporter
              tag: latest
            env:
              MONGODB_URI:
                valueFrom:
                  secretKeyRef:
                    name: *mongo_db
                    key: MONGO_URI
              MONGODB_DATABASE:
                valueFrom:
                  secretKeyRef:
                    name: *mongo_db
                    key: MONGO_USER

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3080
          metrics:
            port: &exporterport "9123"
            targetPort: 8000

      meilisearch:
        controller: librechat
        ports:
          http:
            port: 7700

      ragapi:
        controller: librechat
        ports:
          http:
            port: 8000
            targetPort: *rag_port

    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: AI
          gethomepage.dev/name: *app
          gethomepage.dev/icon: https://raw.githubusercontent.com/danny-avila/LibreChat/refs/heads/main/client/public/assets/logo.svg
          gethomepage.dev/description: "AI Chat"
          gethomepage.dev/href: "https://chat.${SECRET_DOMAIN}"
        hosts:
          - host: &host "chat.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      init-db:
        enabled: true
        type: configMap
        name: librechat-initdb
        advancedMounts:
          librechat:
            init-db:
              - subPath: librechat.sql
                path: /initdb/ai-librechat.sql

      config:
        enabled: true
        type: configMap
        name: librechat-config
        advancedMounts:
          librechat:
            app:
              - subPath: librechat.yaml
                path: /app/librechat.yaml

      app-data:
        enabled: true
        type: emptyDir
        advancedMounts:
          librechat:
            app:
              - path: /app/data
              - path: /app/api/data

      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp

      data:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM:-${APP}}"
        advancedMounts:
          librechat:
            app:
              - subPath: logs
                path: /app/api/logs
              - subPath: images
                path: /app/client/public/images
              - subPath: uploads
                path: /app/uploads
            meilisearch:
              - subPath: meilisearch
                path: /meili_data
            ragapi:
              - subPath: ragapi
                path: /app/uploads

    serviceMonitor:
      app:
        serviceName: librechat
        endpoints:
          - port: metrics
            scheme: http
            path: /
            interval: 1m
            scrapeTimeout: 30s
