---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hr.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: librechat-config
    namespace: ai-librechat
    files:
      - ./resources/librechat.yaml
  - name: librechat-initdb
    namespace: ai-librechat
    files:
      - ./resources/librechat.sql
generatorOptions:
  disableNameSuffixHash: true
