---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - hr.yaml
  - ./secret.sops.yaml
  - ../../../templates/volsync/claim.yaml
configMapGenerator:
  - name: librechat-config
    namespace: ai-librechat
    files:
      - ./resources/librechat.yaml
generatorOptions:
  disableNameSuffixHash: true
