apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
    namespace: database
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: security,home,monitor,network,spring-dev,dataflow
    labels:
        cnpg.io/reload: "true"
stringData:
    EMQX_DASHBOARD__DEFAULT_USERNAME: ENC[AES256_GCM,data:dOLDq9A=,iv:Xg4/KnN+wnQLU+Rpi+ctulmGX1knOfvw25eKniXM2fg=,tag:iNcCn1pFjgXtih6lNhH6wQ==,type:str]
    EMQX_DASHBOARD__DEFAULT_PASSWORD: ENC[AES256_GCM,data:qwjrfMM=,iv:bAzGq/fnnoEzxSRar4NW4GbSt/M9cXzeWW05MX5Rcqw=,tag:STdEEfj6lbUS0RnLxHwEhw==,type:str]
    X_EMQX_MQTT_USERNAME: ENC[AES256_GCM,data:aOw9hMrixNX1,iv:r0YQ8MsodK2dx3aa85VWwRYg1Zm4T4CW/9vBkTqNrvk=,tag:H0kMDUKsfW09vmbjeN3unA==,type:str]
    X_EMQX_MQTT_PASSWORD: ENC[AES256_GCM,data:DJQw1d97vYOUAc9EX4qTJ1y0mDW7ifVk,iv:OzTpywVQiaYTt69VQh9ntEN3UnzJnCkfGJ/pZ75HfqU=,tag:ZLJscHyPZTFxaCKjtRl35Q==,type:str]
    X_EMQX_APIKEY_KEY: ENC[AES256_GCM,data:JHxeBP0JrJfAuEcHQRwxEoRJqIu2EaO1,iv:XAR5l13oVFhwBv1bN8JHnZ2wqqQKCZfV0wGc1IEoE4k=,tag:KKa8UKffA5eOIyakezQNqQ==,type:str]
    X_EMQX_APIKEY_SECRET: ENC[AES256_GCM,data:L2HELG0zatMvMOU9HT9OogzwDOKQOjmA,iv:Ayh4PYr0876X05XYRqjGeoo4/GDNTON4AytmhP2Wdmk=,tag:d/6Ps5wqqcfezDhWjGHndg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T14:19:07Z"
    mac: ENC[AES256_GCM,data:1vVmrAde400Mgi97vvFbASmhHcedO9G+Huz2utniPSmuKmhkIO+726Rzjjek3eAwyCGW8FK4/pJ9Ucao3uhhjoTdHFEjxHnrlKcp/U1ORoCgfjnH0Q8x+tqrc2jI+vDXCp5G71AAhBCIsUII2JLD7PYi7FKR5gMNCbsfAei1cjM=,iv:aLv/NV5UjxlmZpJEh9dTW9VXPIgOFJLg9VLVCu+FTdI=,tag:zs4Rb8k8tNvdHL6PIJWxsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
