---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-kubernetes
  namespace: flux-system
spec:
  interval: 10m
  url: "ssh://git@github.com/sergeybataev/homelab"
  secretRef:
    name: github-deploy-key
  ref:
    branch: "prometheus-monitoring"
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
  labels:
    kustomization.flux.home.arpa/name: "flux"
    kustomization.flux.home.arpa/default: "false"
    wait.flux.home.arpa/disabled: "true"
    kustomization.flux.home.arpa/helmpatches: "false"
spec:
  interval: 10m
  path: ./kubernetes/flux
  prune: false
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          interval: 5m0s
          timeout: 10m0s
          decryption:
            provider: sops
            secretRef:
              name: sops-age
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          sourceRef:
            kind: GitRepository
            name: flux-system
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: kustomization.flux.home.arpa/default notin (false)
    - patch: |
        - op: add
          path: /spec/dependsOn/-
          value:
            name: cluster
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: kustomization.flux.home.arpa/default notin (false)
    # - patch: |
    #     - op: add
    #       path: /spec/dependsOn/-
    #       value:
    #         name: monitoring-prom-crds
    #   target:
    #     group: kustomize.toolkit.fluxcd.io
    #     version: v1
    #     kind: Kustomization
    #     labelSelector: kustomization.flux.home.arpa/default notin (false)
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-config-versions
                optional: false
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          prune: true
          # prune: false
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: prune.flux.home.arpa/disabled notin (true)
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          prune: false
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: prune.flux.home.arpa/disabled=true
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          wait: true
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: wait.flux.home.arpa/disabled notin (true)
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          wait: false
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: wait.flux.home.arpa/disabled=true
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          patches:
            - patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2beta1
                kind: HelmRelease
                metadata:
                  name: not-used
                spec:
                  interval: 5m
                  maxHistory: 5
                  install:
                    createNamespace: true
                    remediation:
                      retries: 5
                  upgrade:
                    cleanupOnFail: true
                    remediation:
                      retries: 5
                  uninstall:
                    keepHistory: false
              target:
                group: helm.toolkit.fluxcd.io
                version: v2beta1
                kind: HelmRelease
                labelSelector: helm.flux.home.arpa/default notin (false)
            - patch: |-
                apiVersion: helm.toolkit.fluxcd.io/v2beta1
                kind: HelmRelease
                metadata:
                  name: not-used
                spec:
                  chart:
                    spec:
                      chart: app-template
                      version: 3.1.0
                      sourceRef:
                        kind: HelmRepository
                        name: bjw-s
                        namespace: flux-system
              target:
                group: helm.toolkit.fluxcd.io
                version: v2beta1
                kind: HelmRelease
                labelSelector: helm.flux.home.arpa/app-template=true
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: kustomization.flux.home.arpa/helmpatches notin (false)
