---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-kubernetes
  namespace: flux-system
spec:
  interval: 10m
  url: "ssh://git@github.com/sergeybataev/homelab"
  secretRef:
    name: github-deploy-key
  ref:
    branch: "main"
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
  labels:
    kustomization.flux.home.arpa/name: "flux"
    kustomization.flux.home.arpa/default: "false"
    wait.flux.home.arpa/disabled: "true"
    kustomization.flux.home.arpa/helmpatches: "false"
spec:
  interval: 10m
  path: ./kubernetes/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
