---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./hr.yaml
  - ./rbac.yaml
  # - ../../../../templates/gatus/guarded
