---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-it-tools
  namespace: flux-system
spec:
  path: ./kubernetes/development/it-tools/app
  targetNamespace: &ns dev

  commonMetadata:
    labels:
      app.kubernetes.io/name: &app it-tools
      app.kubernetes.io/group: dev

  postBuild:
    substitute:
      APP: *app
      NS: *ns

  interval: 1h
  prune: true
  retryInterval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn: []
