---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# yamllint disable rule:comments
# prettier-ignore
resources:
  # Pre Flux-Kustomizations
  - ./flux/test.yaml
