apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1D5JTdtgOD6nfKU=,iv:kErvnMiegfPsOo3SRVOoyp5SvDz8ZD2m9GeziwGGYZw=,tag:eNJ6jKM2aCklFwYM+LFGww==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Tc+W1jYn+hCgp+1lYVbDPZo=,iv:Z1ag3mUXR4KmrdA86NrWq9TYcMGrnmXx7M0JDR7WWmg=,tag:3D57c0TuePrAJZjfEQC6Pw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:GOh+hSdGPWMBBKrGZDevlOQnbfjCG/6d4kekIoGoFQ8HG72z,iv:vRa9jVH20rB5TLBQqdSZHusJOa20KbDW0La/E0i1XpQ=,tag:8w/H+lPxftWwkcoWa4t8Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T18:46:01Z"
    mac: ENC[AES256_GCM,data:88TRcuWkaUqobJA0F4libIC9i2WOagUGzqbuvy9JAys9s53u2xH9Uo9ZGRKkoSBfmBz/JG2uQZ3EKGJpbKIcF9Q+mT7K1HnzD9HPi74uHDHcv86j4NcxXv10nBBBziE2/0HJeCMfdwlrkeeKvIxCwCCvYMOPielwuK96Gy/FHXI=,iv:R3Xzf5wKYRErHSWVsv9G79SrZlDnThz3BA7s83iyU9w=,tag:XiCG1PIO6MwUwoHlfvis2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
