apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:kD5yk1/WmEjnBeoBFFMFIJymaBbGSSE45Su2LaVBXneVPryjdhOstWOgGWh0YHu07yXB6M7XL15Pa1vN6JirvNtudOM6eCVgy/kKsqfBuqZJIiMgKflt4QgRBE0rGQ==,iv:CR055nJhcIztM1U4gCyusBKzHigA/BgEe28eNFDWiYk=,tag:EFhs8smxcuxFWH+YO1qoAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZGliQXZQdDdKZkx6c2FG
            S2tLTFBuVHRQcWJRRDBhYnJwL2dPenh4WWhBCjk2Q1pKM0pKNFNiMzhTb1RoR3F2
            MUhFeldRWDJKeW03QlFKckRDM2pYdkEKLS0tIFpWTEw5cmlNdkFTU1A4c3VHc1A3
            ZUs0R3c0UHVqSXNCZEF3M2ZtU0JPNWsKWevkCPjKp1Ucr1ObkdC9HEJBSTX+1eUt
            AKQpwq2dsmTwAPhwxkqeXbtjU2Js6sl68TOAGS2LMWFdSzCOi63+Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T00:03:47Z"
    mac: ENC[AES256_GCM,data:ZsSQVTO9zUfWU5/PinsUhCVDNNLRxl47eSaf/Bs3YHHMRdbTwYd3FQxqHolKbvxB8nahfSRPloc0XMxAuC0coI98fuSmWNgCRCSTIV6ytpkeKUI7JHDYsTl7MW4nnpQrHm9E/zKb5lsYtI3VYCThXpOvj3jXPRx8YY0FL/ObsuE=,iv:nUsBrfmRXBOHN9Z8rGX4M1Bf2usaigpviwRun4jIPFg=,tag:G63WFmhuHOSpKkNtNUro1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
