apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:jTuU6Mw9mT6nJ+DsEBAJ3f2bjst3usQ/Vclqi++bSUwgF9wGXAvpJUay+VsN5wEtXmhoOZCe/tbgrOJVZH/Oo51kNqPGi0/soNPKG9OLBZoyBObu43TuRUTbYciTKA==,iv:KldTtphGsCuekAtgewkT1kmAvPRJNjH8L+C5vhc82eg=,tag:GTZnxeVHrFHJfHltcmXVkA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:rd7HAdKQVihSPg==,iv:IrLfD/4ZBSxCn5pWxpttD7Ox8jCMOrzhKydEvL26PFk=,tag:Vl60Hl+/dJKgT0VyBuqeaA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:07KKVDC8akysMporHGQuAms=,iv:78bJSM1TVuIuhZrT3we1nc4EEiruL5/czha59wOk1C8=,tag:IQYX9LhlWwU3MSeBjhMWsA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:aN+HEq3tIPtCMODrXvT0CoGsqQq776TEB3yKHD8IUp5DoQBE,iv:1fGoCWKYmncA33ZjkjRBo53P9xXF1qROBVBBbVsz0BA=,tag:5YiRyHztzUkCv8WJ4bCVVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnxm438gfmv6kg658crenxxzad3krnytqqdlseyues9um26meyus7cnla9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreUlQQ0FLQVNNaFloRCtk
            UmxWOWsyNVQ5N0tJSW12Mm9Bcm9qK1l3bXdrCmxjQllSNEZ4SE9wUmRWWlBWUGFW
            M0hHTHR2U25BOCt4MFpZcVYyb0U0WU0KLS0tIDNBZVh6MUt4L2dxZzljSUIrRXpn
            dHk5VDJqL3l2ZTRHTUJvdUlac3gxS28KCnM6G6oBUY9ri5+sGGtHmAY7ZIuEyttK
            yw2kaY/OlDMssNgkKg3kgTb4BOITwjzFfgcjNhCEjqgYTngScPE2lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-11T10:54:41Z"
    mac: ENC[AES256_GCM,data:9bL/PWgW9++U8NnnNoCKTGCKjuSFqtI2hgQ5O0SnePV1aKB3tCgzWs+BKgc2tk4jtZw3z0Saom5pEcTg3EiLEBjNMaMRZe64KrVJpI89iAoA++hZPzMvRq63XaR043ZicuwVubTcoqrpt/G7j27xSEHB9zBTuCDAccfxwaOfAeA=,iv:Vgp8bWHbvyvkHHuCmWREM61qp0kIxmmbfLC4elkKtdk=,tag:tooyyIRQSu7XG95qG12+nA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
