---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Helsinki"
  CLUSTER_NAME: "homelab"
  CLUSTER_CIDR: "172.16.0.0/16"
  NODE_CIDR: "192.168.0.0/16"
  # 192.168.4.*
  K8S_GATEWAY_IP: 192.168.4.1
  CLUSTER_CONTROLLER_IP: 192.168.4.2
  INGRESS_EXTERNAL_IP: 192.168.4.3
  INGRESS_INTERNAL_IP: 192.168.4.4
  # 192.168.4.5
  PROMETHEUS_IP: 192.168.4.6
  CLOUDNATIVE_PG_IP: 192.168.4.11
  GRAPHITE_EXPORTER_IP: 192.168.4.15

  CLOUDNATIVE_PG_IP_2: 192.168.4.50
  MONGODB_IP: 192.168.4.60
  HOME_ASSISTANT_IP: 192.168.4.123
  EMQX_IP: 192.168.4.200
  CLICKHOUSE_IP: 192.168.4.201

  BACKUP_NFS_IP: 192.168.4.221

  # Home
  HOMEPAGE_IP: 192.168.5.1
  PLEX_IP: 192.168.5.3
  SYNCTHING_IP: 192.168.5.4
  HASS_IP: 192.168.5.5
  HASS_POD_IP: 192.168.5.123

  # IOT
  IOT_GATEWAY_IP: 192.168.255.1
  IOT_HOME_ASSISTANT_IP: 192.168.255.2
