apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:tIdeRO05FaUl0h1GO2CY55si2yuziIABstjrReUWiCmB8YCGZbUFw8ZqE1C9uqz03MKPtGwnp0U8ytYeCnjfy2vAWinD8iGsmbXrk76Z0AEh9Hf/yUIrKI1x4M/V+Q==,iv:ixzHcVE8SYCYOz7vjoa/4FEusY/lTRHadtGOaLFSz10=,tag:KoclDHukX5QlkIkodNu44w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVanlFaEZ5eDBwZzlBWmxP
            bTBncXowLytZTHdHNXFPTEQrZjFpMHJNeGdVCjhPUVM0UmZCeFduZFJVTk5WZXlT
            OE85amkzcVVoSlgwUDBXYUl5OXFZVEUKLS0tIFpvdkJlVkJDS1p3aTlCdjRRR3Rs
            dlpnTGpZV0Y4ZithUlJUU1paem0wVVUKUO11GLUUXXSVCXf1MjRC42I2occtPCoa
            7gS/dDdtKm/PHA9EzIcYwjTsCkvwuY7ScjiG/S+Rl3on0XFApXtEvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T19:18:35Z"
    mac: ENC[AES256_GCM,data:vejXXul9k4CorHrmZIFPHr0Nap1wt5N3UzlP45U7d7vkOY3w5JdG0+X4/P/0IyDhUrLrysKMw7122hz/XJycJcitWK+UZOyra1SQbie385ikQjuGkQtGIxmEIJmHRdiOUmhOa+L0zlIWs5XlQQl5P8FrMWcGiLwmuDExo1eOYyU=,iv:2UFnEcTRK3jf51jqWhBp/J3lpZfUoQZkuwJi70Fdufs=,tag:onQUGGvklzMKu9O6hBUy2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
