---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Helsinki"
  CLUSTER_NAME: "homelab"
  CLUSTER_CIDR: "172.16.0.0/16"
  CLUSTER_CONTROLLER_IP: 192.168.4.2
  K8S-GATEWAY_IP: 192.168.4.1
  LOCAL_DOMAIN: home
  EMQX_IP: 192.168.4.200
  CLOUDNATIVE-PG_IP: 192.168.4.11
  GRAPHITE-EXPORTER_IP: 192.168.4.15
  # PROMETHEUS_IP: 192.168.4.6
  INGRESS-EXTERNAL_IP: 192.168.4.3
  INGRESS-INTERNAL_IP: 192.168.4.4

