apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:XMCFd9wxmFOQHbCvr0OuqTvAR8z8NFevB5t1EFmGJQvLkhWCFUp0pZYMDBtME2FwRaJrdaKkBuo4tbpOHbLsYMNed0knJLIXzRoGqRJ2/hugn1Pw7fkXUMLee84WQw==,iv:IBPgzUzChorabLN8mxNVS5iD2UyJwa/5Kwn4Nc0CBiY=,tag:jtycOQjaGRpL3vUPj9IR2g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:V1ac9FqFeLw2Q0s=,iv:GJOpGUTESpdherMpbeUUxhsOvZ5Md6mfBFtDZydpSYY=,tag:J6dDsGlxHukW3oqfDfJS6w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:MPRwDHiMUBUIudHKgqtuvTU=,iv:p0mOq4Dd1h9g3xkfx1RzV14SEyIJCSlBrsWVNzb/BMs=,tag:AXuWJNjpsOTI+bxVXzrLUw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:BLcEZWhlXsUqj8laYFIwMUAPapEiTJICq56uzCdkL6U/nhKB,iv:rnnYKk5CC3ilxLrmByMTHFMyE5Sa8vVN7ZrQZ5XqjN0=,tag:Vx56Mp5d3X6/KD/+6fAiCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBub0tJNmVhdXNtdTkyb0Fi
            eWh2aURTZUs3T3ViaGpBU1RTVmZ3N2RMNDJVCnJ0cnpGS2V3STZGdXdpbk5nT0dJ
            K1h3QkxuS2dvLzNLQTZMQ2xTRkUrSmcKLS0tIHF4NTNsUXRhalpQdDFHRmNOUVdE
            eTArQWtpRTFPMjBRempsbGMrVE03c0UKqUUF5PvYeLZW5rPXJtmclrVP36Lzy02X
            PoRrVQqR7ge/EbH586heQQk7BTdmZNJ/b6PF2IdRl64tpF0+NeNz0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T13:15:02Z"
    mac: ENC[AES256_GCM,data:uTMtT6xlitpTRJehBzNFrH6oEpmV1FeVE1V5UJf6LTv1nmnoXkadhPIgGwfmOnVZMkOBwFYlUmac4fB2/OnmKyf6Zxry8h63z4H1CTmjkXRVlHDvLjhBLV69Ne1web7d4fT5y2/nZnyW7An2RYJqDyHwbDRvnh/+wUhAEtcrx04=,iv:6TRWnxMqSzsSqHWFpcVcSBJg/2o/eehAOzMUyv/v1go=,tag:AxbA5WkZ7ymWMM9mApF52A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
