---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Helsinki"
  CLUSTER_CIDR: "172.16.0.0/16"
  CLUSTER_CONTROLLER_IP: "192.168.1.10"

