apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:HHuEH6mst0390+igaa0WzjJIiey2s5Ul5j0C3AjboUdYWQCp7yazqSkrj7qT4CF+CZ00owHp9pmvEMq8i1S9EiZaF8DbONk4/zmbZ+1w0MAQ/bhkqW3/YkA/VFp9OQ==,iv:kTLb0MMBNAReWnBiA3PB/LpsPIlq/X2qM1GMoOIlfWk=,tag:SY+0Ed85VGa6/gB3nhIyqw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:bLSe0iVfCJomKA==,iv:8dZyazVmNgYh7BFdxpmFGg49lf93MVNYmxg2j500PEA=,tag:7kEA69wVrDMA1u3Z/7dngA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:or87k5IKB1yFZD0f9QHLjuQ=,iv:I9ecAHKM6ffacdRBt9KWfOlyujPnpkJNhzmmkV2iWX0=,tag:Rg2ge2d2S7dem6eVZqOkuw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wVmrYrrH/+9MV6+GdcaN2gs1PIFmOkI3Fy9/dOKznXIwLC8x,iv:uuvytTVL70xLOZoiegpZOBchwVM7a5b3B+xSdtJeC/I=,tag:KG8GAEO69uWTJTfw5YviLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSXNtK2x1cHI3UHVlcVBv
            OWY0dk9sdVRSb25ZU3RxSmVPMkhodXMwUHdNClViWXliUklaUE8xRmsrSmkxL0ls
            N01CdEZsd05MT0pnZ0d4eG5acVNBTlkKLS0tIElrZC9ub1ZTemhqbkJxNDFtbEVW
            UnZ5M3daYm1NWE9NM1dXcjMvaVE5YUEKhsD6Pf1M5HP/6keR48UErVnYIxVeOmrH
            UNB7QqznkDgCLmGwPOFmvEZmOpz+7Z0OWBLs3ggaYHzAsSNPKt+QWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-11T22:34:25Z"
    mac: ENC[AES256_GCM,data:NYn3RGkDQR/gNDb/r1JoNHKuy7waHVAy6xytc7an9QZ+xEySuzXwTzt45wF5F8JyAzkFPr0axOCm6HdZB4ti0rIwqO3hnrp4rPZMWKcb9zLAne/boXKRvo8k2/P4Hti6QbmrRwB3oLt9wgEweUYwgqGgRmOMMf6HhS8iSN9TSro=,iv:iWtKOrfU6FZMY4VcgRrEKRE98exbMgQ56aga0M5mBQE=,tag:QSvWtftdF5W2VdJ0Fv+0jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
