apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:GD44ybjOTts5OipCzw6UGOt+/px7rTJEl5VTQYA2gL6OdAHczltC0YJ82VYbfwGPtPtzRPnHUnf+f+oeW3raQpjlkc5eMK9OAEQaJ7ZQJhnBKF65Lq4EQBs+ue5R0A==,iv:POGfeN8TlRzkSQf3+5p9TZp9JHjazFA1eMTxDkFau/A=,tag:5vM+8Js2QCmXWtsF9W2tTw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:1D5JTdtgOD6nfKU=,iv:kErvnMiegfPsOo3SRVOoyp5SvDz8ZD2m9GeziwGGYZw=,tag:eNJ6jKM2aCklFwYM+LFGww==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Tc+W1jYn+hCgp+1lYVbDPZo=,iv:Z1ag3mUXR4KmrdA86NrWq9TYcMGrnmXx7M0JDR7WWmg=,tag:3D57c0TuePrAJZjfEQC6Pw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:GOh+hSdGPWMBBKrGZDevlOQnbfjCG/6d4kekIoGoFQ8HG72z,iv:vRa9jVH20rB5TLBQqdSZHusJOa20KbDW0La/E0i1XpQ=,tag:8w/H+lPxftWwkcoWa4t8Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-17T17:12:40Z"
    mac: ENC[AES256_GCM,data:WOcY4Hgac1Q2s3/bqqyrSNqb7FO12H/o5t4v/bNdQn+G+1SjbIGquQHWyaXhw433QqYllAT9Ii6CkX3YYC6rMbaSkNs5+0oVpQ1tUW6okZzJS8joLTTUuPPxJIepSjG1V37qFx3DhTOQwxKBm5dZaUX/64ZErCSj4t6fm4pt69w=,iv:g/+BtewjQY9FkRB1b6IDUT76Qx0rfA498ObK5A+XXms=,tag:g2NzueqGe6+rNClWkdvNiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
