---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Helsinki"
  CLUSTER_NAME: "homelab"
  CLUSTER_CIDR: "172.16.0.0/16"
  CLUSTER_CONTROLLER_IP: 192.168.4.2
  K8S_GATEWAY_IP: 192.168.4.1
  EMQX_IP: 192.168.4.200
  CLOUDNATIVE_PG_IP: 192.168.4.11
  GRAPHITE_EXPORTER_IP: 192.168.4.15
  PROMETHEUS_IP: 192.168.4.6
  INGRESS_EXTERNAL_IP: 192.168.4.3
  INGRESS_INTERNAL_IP: 192.168.4.4

  HOME_ASSISTANT_IP: 192.168.4.123

  IOT_GATEWAY_IP: 192.168.255.1
  IOT_HOME_ASSISTANT_IP: 192.168.255.2
