apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:ibm/GXzW3jvuaA==,iv:UPyAd1N76kpv8vALo8piMAm26FU/R5NrKngk1PJ2/pQ=,tag:9bAZ/cALHSAwrNImHjY1iw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:1D5JTdtgOD6nfKU=,iv:kErvnMiegfPsOo3SRVOoyp5SvDz8ZD2m9GeziwGGYZw=,tag:eNJ6jKM2aCklFwYM+LFGww==,type:str]
    SECRET_REGISTRY_DOMAIN: ENC[AES256_GCM,data:8vg4itUYnq+PGNl/j8B9zidmY7A=,iv:FpF0pHs90DTSLi+e/M6urqQttVc3M389N0Duln0r4PE=,tag:2JyJB34yfN8rX3aafU8pEg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Tc+W1jYn+hCgp+1lYVbDPZo=,iv:Z1ag3mUXR4KmrdA86NrWq9TYcMGrnmXx7M0JDR7WWmg=,tag:3D57c0TuePrAJZjfEQC6Pw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:GOh+hSdGPWMBBKrGZDevlOQnbfjCG/6d4kekIoGoFQ8HG72z,iv:vRa9jVH20rB5TLBQqdSZHusJOa20KbDW0La/E0i1XpQ=,tag:8w/H+lPxftWwkcoWa4t8Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-24T15:15:26Z"
    mac: ENC[AES256_GCM,data:ZTuwyCucPhiAhZ516vNhT1bn9Tk+PrrKbpoJvJUxvXrjQlkhFXuNCU/V8qStfFcbN8yewa9pAsXjYq//uvwg6jWmxWzR1JwqJidqJiMN+uCzmcUkyVKPbNxcSjFC/W2ELzyHhUjjN7K1NaTS8oGWT8SQn298yFlliGgFDGtHD2A=,iv:j9HDQj4QLqoggFhFUBQfatIX3Qyoky/3CLJFgmlt3+Q=,tag:G99lQFFQxNbdckMCoEbmrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
