apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:ibm/GXzW3jvuaA==,iv:UPyAd1N76kpv8vALo8piMAm26FU/R5NrKngk1PJ2/pQ=,tag:9bAZ/cALHSAwrNImHjY1iw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:1D5JTdtgOD6nfKU=,iv:kErvnMiegfPsOo3SRVOoyp5SvDz8ZD2m9GeziwGGYZw=,tag:eNJ6jKM2aCklFwYM+LFGww==,type:str]
    SECRET_REGISTRY_DOMAIN: ENC[AES256_GCM,data:8vg4itUYnq+PGNl/j8B9zidmY7A=,iv:FpF0pHs90DTSLi+e/M6urqQttVc3M389N0Duln0r4PE=,tag:2JyJB34yfN8rX3aafU8pEg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Tc+W1jYn+hCgp+1lYVbDPZo=,iv:Z1ag3mUXR4KmrdA86NrWq9TYcMGrnmXx7M0JDR7WWmg=,tag:3D57c0TuePrAJZjfEQC6Pw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:GOh+hSdGPWMBBKrGZDevlOQnbfjCG/6d4kekIoGoFQ8HG72z,iv:vRa9jVH20rB5TLBQqdSZHusJOa20KbDW0La/E0i1XpQ=,tag:8w/H+lPxftWwkcoWa4t8Eg==,type:str]
    #ENC[AES256_GCM,data:niqZ8XKl,iv:iKwBT+iyTujSTjpvR7MQYXzi61sa4UOJNrj4pvqHWTU=,tag:Wk0BRaFq7G4XSiXrlRzSeQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/2DnFSM=,iv:0GtbakXW4flrVnrtCx0920KW7GaCfACWrsEcuHmRG5o=,tag:9Zc4TVX8BaJWu2z4zR7Pfw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:U5HQDpiSv1I=,iv:flOKuQRlx+NYs6bRHZrk9d47rNn/Wbh14Bepx01sLdU=,tag:oVJ1WkvN/Heu1qxNDUDMtg==,type:str]
    #ENC[AES256_GCM,data:pA1Deu/dXnog7HhnBCiHdAqcwA==,iv:+A19VnphwbAptxF8SvqI/TwEjEjknyzgRjOnzzLow5s=,tag:WjIyWP8Rx0IZZSeiu41/nA==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:WTsHuOe0wclwDx8EJcGgEYyzeocGSzsxZuUHHKh+YCE2n1l0TDNv,iv:n9MGR+aixpg4vQDy9knai2O2f/m2V60RK6IqEwu1+4E=,tag:fQTMqlid8lxXMO6nNz7s6w==,type:str]
    #ENC[AES256_GCM,data:4t9ARRlHwWiRlMLx9r5wWyAHED2XzIp+pKngLtkW,iv:9kMpFLVObJ9zioY2HhXj6Gq1eHdBBcN4TivJZX46+0I=,tag:Ci2R3l+LmW6plGT6Au7eug==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:yKJzt2WnNNJNqyzhSLIq1wq6KLfuymszgA==,iv:ZgLP/lUCAJC0FWLyLB1OMs0Zvt/5zH6boNC9Qg3ClAQ=,tag:Hgsd16DnPag8y9/0cwbYtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T12:03:54Z"
    mac: ENC[AES256_GCM,data:3sZvlqWx6DIUAKAUsWzt2+uGABGNgWmozEbzsbru92h2S8OBq0+xCMUEjo8KK1Awfmb53ogdvK49SV+uJ8t6pEe3MPn+xzU/YTIFP5dwTilOezK4JYN2PCg2z0iX9b7VlwjIcKD/0eZb2udKQIqqXEYLdcxBLrDrpRwEE2VZT3w=,iv:CS+eoL7E1zP/HqNIfOsYk2Goe7k7AyrUf2HQJcbVbBM=,tag:6EMKZYKe8dwzFKMftVurSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
