---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./openebs-system/ks.yaml
  - ./rook-ceph/ks.yaml
  - ./volsync/ks.yaml
  - ./node_main/storage/ks.yaml
  - ./minio/ks.yaml
