apiVersion: v1
kind: Secret
metadata:
    name: unpoller
stringData:
    UP_UNIFI_DEFAULT_URL: ENC[AES256_GCM,data:V4/VnpJFA28uRtY=,iv:ovylfvKKDTNVQ7aIiHVxpxAZUc6lHEON+yfkdNYHNcs=,tag:XLcRZyguJyyT3i8WLk7wSw==,type:str]
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:HhW2eLd2ZC8=,iv:dZj5J+7Cc6kx9hlqNZAntDxc5AoTw9gd5oY1egwEds0=,tag:w2mMoFCfWcNIjUH4lCVW7w==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:afMTcdKd+I4C90GUrm5f6LaWNft49KT/,iv:hZD2xA/dFf8RhH5l50T7u7BDEvob4SDbHPN4qECnVes=,tag:ATWpWyMNuBL17H81QcW4VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-03T18:27:06Z"
    mac: ENC[AES256_GCM,data:kM0g367Tb6QPaWlEJ5A9uvOiJGCd0aWxJOcePaOG8Il9X4Yl2qpZt4KFCaqxta9246T+xFY68msCw2tjYCJnQVBwenpjbRYvwySOmx3GFgt0sGfDebLkqOOMUCxluO9wse3K8Vmo2M+fv4aXXVIw62W3GFei4UtD7E/APyrq4Gw=,iv:VkGI/qNjqk90ki1jx1lWjlRMuVDRtIRq9Ljs+ZJWpME=,tag:PgKgSKxYe9ilv2Y1HhKFAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
