apiVersion: v1
kind: Secret
metadata:
    name: unpoller
stringData:
    UP_UNIFI_DEFAULT_URL: ENC[AES256_GCM,data:ivnBkIs1/Mwvy3A4aJUaZCt3fw==,iv:IO0yOuKHpc0svalbY0CkDSgDIVFgwnf9R9dAJeOlVCU=,tag:0JAZ3+mpyUS5tYGkxw9LnQ==,type:str]
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:HhW2eLd2ZC8=,iv:dZj5J+7Cc6kx9hlqNZAntDxc5AoTw9gd5oY1egwEds0=,tag:w2mMoFCfWcNIjUH4lCVW7w==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:afMTcdKd+I4C90GUrm5f6LaWNft49KT/,iv:hZD2xA/dFf8RhH5l50T7u7BDEvob4SDbHPN4qECnVes=,tag:ATWpWyMNuBL17H81QcW4VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T18:25:33Z"
    mac: ENC[AES256_GCM,data:mIw0gkvgoEP1to8VK9EesfSghEoVBv1BISnm/Q4zfNh5AxUmmyqFBtZ1nsV464BQ5z17STz2LGRtKI4txbDVjIZxL6b/AJbErld018cN7Ug02WYmZTDQ5VLwoU7HeicTLVxUDEXQPLSlI11I/p5Dmo/FaQCbb1wlH9AWK7Y4ptE=,iv:EUILanuKnEHPPSS1KY08Sgjhc5ZmInde63f/+iYL8lA=,tag:8/fPq9sCucx4u2o8/Ob/8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
