---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-mongodb-operator
  namespace: flux-system
spec:
  path: ./kubernetes/database/mongodb/operator
  targetNamespace: &ns database-mongodb
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app mongodb-operator
      app.kubernetes.io/group: database

  dependsOn:
    - name: cluster-storage
    - name: cluster-network

  postBuild:
    substitute:
      APP: *app
      NS: *ns

  components:
    - ../../../components/ns

  interval: 1h
  prune: true
  retryInterval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-mongodb-cluster
  namespace: flux-system
spec:
  path: ./kubernetes/database/mongodb/cluster
  targetNamespace: &ns database-mongodb
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app mongodb-cluster
      app.kubernetes.io/group: database

  dependsOn:
    - name: database-mongodb-operator

  postBuild:
    substitute:
      APP: *app
      NS: *ns

  interval: 1h
  prune: true
  retryInterval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
