model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/SECRET_OPENAI_API_KEY
  - model_name: chatgpt-4o-latest
    litellm_params:
      model: openai/chatgpt-4o-latest
      api_key: os.environ/SECRET_OPENAI_API_KEY
  - model_name: o1
    litellm_params:
      model: openai/o1
      api_key: os.environ/SECRET_OPENAI_API_KEY
  - model_name: o1-mini
    litellm_params:
      model: openai/o1-mini
      api_key: os.environ/SECRET_OPENAI_API_KEY
  - model_name: o3-mini
    litellm_params:
      model: openai/o3-mini
      api_key: os.environ/SECRET_OPENAI_API_KEY


general_settings:
  store_prompts_in_spend_logs: True

litellm_settings:
  # # Networking settings
  # request_timeout: 10 # (int) llm requesttimeout in seconds. Raise Timeout error if call takes longer than 10s. Sets litellm.request_timeout
  # force_ipv4: boolean # If true, litellm will force ipv4 for all LLM requests. Some users have seen httpx ConnectionError when using ipv6 + Anthropic API

  set_verbose: True # sets litellm.set_verbose=True to view verbose debug logs. DO NOT LEAVE THIS ON IN PRODUCTION
  json_logs: True # if true, logs will be in json format
