---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ${APP}
  namespace: ${NS}
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  targetNamespace: ${NS}
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: *app
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
    controllers:
      litellm:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.8
            envFrom: &envFrom
              - secretRef:
                  name: litellm-secrets
            env:
              INIT_POSTGRES_SUPER_PASS:
                valueFrom:
                  secretKeyRef:
                    name: cloudnative-pg-secret
                    key: password
              INIT_POSTGRES_HOST:
                valueFrom: &db_host
                  secretKeyRef:
                    name: cnpg-main17-secret
                    key: host
              INIT_POSTGRES_USER:
                valueFrom: &db_user
                  secretKeyRef:
                    name: litellm-secrets
                    key: DATABASE_USER
              INIT_POSTGRES_PASS:
                valueFrom: &db_user
                  secretKeyRef:
                    name: litellm-secrets
                    key: DATABASE_PASSWORD
              INIT_POSTGRES_DBNAME:
                valueFrom: &db_name
                  secretKeyRef:
                    name: litellm-secrets
                    key: DATABASE_NAME

        containers:
          app:
            image:
              repository: ghcr.io/berriai/litellm-non_root
              tag: main-v1.61.13.rc
            envFrom: *envFrom
            env:
              TZ: "${TIMEZONE}"
              LITELLM_LOG: "DEBUG"
            args:
              - "--config"
              - "/app/config.yaml"
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: true
            #   capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 200Mi
              limits:
                memory: 600Mi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/liveliness
                    port: 4000
                  initialDelaySeconds: 30
                  periodSeconds: 60
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/readiness
                    port: 4000
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 3
    service:
      app:
        controller: *app
        type: LoadBalancer
        ports:
          http:
            port: 4000
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/app-root: /ui
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:math-compass
        hosts:
          - host: &host "litellm.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config-file:
        type: configMap
        name: litellm-configmap
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
            readOnly: true
