---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hr.yaml
  - ns.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: litellm-configmap
    namespace: ai-litellm
    files:
      - config.yaml=./config.yaml
generatorOptions:
  disableNameSuffixHash: true
