apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ai, ai-librechat
stringData:
    UI_USERNAME: ENC[AES256_GCM,data:4yFjM3Vznw==,iv:ql6pFN2WFPPkaNV9zZkAsObzYkwRMxGPm0XsUDs+sgg=,tag:+YiWxmiFiYrPiADT89I5kQ==,type:str]
    UI_PASSWORD: ENC[AES256_GCM,data:pKIFRdEH,iv:+8LMV5nWGf0NtiHtgXH4MGl8rBAGQzPTaoIpfCmA9kM=,tag:ydLyvxJI3Lgoq3zSTUNJ+Q==,type:str]
    #ENC[AES256_GCM,data:Rw9J3stbNw3haYcm7WRUCxgjXJw=,iv:JvqEs7jAuZalr7h0hvGQATMVyqjAXi+xI0zwDJx/WEM=,tag:I7S6qT08jnzuVznu7hjsmQ==,type:comment]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:7jvTs9N4thKnrxLHCjXGI19K,iv:7ammZQU3XjIAQUqWbWO+D24fxs10oydDPq+CuBByMqo=,tag:VPZS7JZTRu6ZyFONq2MKNQ==,type:str]
    #ENC[AES256_GCM,data:Rw9J3stbNw3haYcm7WRUCxgjXJw=,iv:JvqEs7jAuZalr7h0hvGQATMVyqjAXi+xI0zwDJx/WEM=,tag:I7S6qT08jnzuVznu7hjsmQ==,type:comment]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:9/6WMVadwGgi2vQ=,iv:ulMa/6Q2xeuBgcJNpUS0ecs8Ab9awh45GJ+MBJiKTew=,tag:cN/3LAgNsxh5rTPXPC6yjg==,type:str]
    SECRET_OPENAI_API_KEY: ENC[AES256_GCM,data:13UEB5/331SuWMAvMOMuZgHMyg2iPHxEIe5L9g1/UvNvaT556J0aDjNBWzIaER9dGqKNYwPeWH7RVqRR3+iHOq7g+0Lma5S0B1BU1a7pEfJ5Vt+yLTQf3bkfHR4Pd3riNFKj7RHoEV2Y1KX75O36iaur2v+EwmuHi92dYMJfYrzpes8KFbL2wLL6j8wZRPvdZHOEXL1MLZVnCJA+/+DA9yCrbCo=,iv:K/UjDzjPfwJHSystZAFw5GYumVEmxgbAASSptPGF4VI=,tag:oIv5h51tWpUd17nji1FhLw==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:unOUrExrU3IbMA==,iv:ys/v7Xc1YWZTtk62fq/CBbdXEbBpDVaftgzf+SnRkxk=,tag:zjeDbmVchWbFBBVG7jbGdg==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:6HZ6w/RGkw==,iv:SjVQkpfEeRbajnxs0iS3zKV9Iygi/2KZiTMR2vlFCCw=,tag:qwItuX6+MxVrSA1RH+NDuA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:aAzO4LhLZkDPSz8=,iv:jL/AS3Yc18Vt9NwStXsAjIVU+5cHmkSgcamYK7sUxsM=,tag:Yq0Ap+OrXN7Z9fHzS+h6Xw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:2u2smSUhLUhmWaQWDgbPVCGRiYFXwVERQ0hfqzWJ/tbC5W9DPfK9D1Wp1CPUbloBhi/EuIyS8VDyfqZoYjk5ZnFP47NRlGeCfkM/tiBCLqeTFrH9dR9J+ljt2A==,iv:XMNNue72ytS6h4YCQCc2CFAGzMrdRcHEypzrazOd4aQ=,tag:8RXWVCKV5Da6WN7hs5A90A==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:yiahgErlTX8I6g==,iv:/PC8wsnX2j5z3BQ/344mzj5WrAc7NjAQLZgj9cAW9vI=,tag:s4AyAykGhiwLXljuBXHLqQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:sOFL7erDNw==,iv:IXj0prrIdWda3SqzWNiTSq2XVrhfNSuI/DgF6lOJEBQ=,tag:UrvxNUsM5E2TnTZkGtezog==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:XQAoNf3IGJAj9Dg=,iv:iTQ3OWNj1v7I8DBzxFVjkuwsOLiTEBu3coKhubqcwuw=,tag:DVCwvzn4eJ2GbV7zumgPxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-22T21:05:56Z"
    mac: ENC[AES256_GCM,data:qEZ6AF18kMiGKBO8R119HX6WoU1zrZrltD0eEwwIDAcIouSMIEyi7eRmsbJ3hIYPHXlHu7fPZm/7oN+wOYr2KnwOxD6q9hvOmaj6VMr2gskEDiatfLWIz+gVP+o3ZtlkK+lp+T6k5F7s4JDM6/a60E9Z5AZuWug+yrYVhWHo4D4=,iv:cEI0MMHOglUjzUvM/tmuYXJNcEKMvU0NQDDtZgNZdqU=,tag:YH/yuM4OSOEKG73sfU6z1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
