apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: ai-litellm
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ai
stringData:
    LITELLM_UI_USERNAME: ENC[AES256_GCM,data:34HdZQuvgw==,iv:Z2gDMBfAh95A1LoyXYV5DbaikVMNbxesAJqgGLt0+HY=,tag:CXaoXosmfCgOpqTjYPObTg==,type:str]
    LITELLM_UI_PASSWORD: ENC[AES256_GCM,data:WGN0vyFc,iv:8mlbbD/KK8m89JhfxkeGJNDpO/qCeQ62k7HzsLMxlRw=,tag:KNSHyquRbr6x5DPbkcvH5Q==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:k+qSkau6koSIYG9BGmIu,iv:aiA/1FDVfP74sadrU37NBO06V4aY6aCZH29x3gJT+lI=,tag:83ZgDatvB7NFxE8zSB8DBw==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:6HZ6w/RGkw==,iv:SjVQkpfEeRbajnxs0iS3zKV9Iygi/2KZiTMR2vlFCCw=,tag:qwItuX6+MxVrSA1RH+NDuA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:XfVysgmIhnQ=,iv:njn+/FZjRb0qFrmA/8Y1oTxpRrxMbG1CcMBHAQwH5/s=,tag:xxRfEyWzaPoZOERPAA4EhA==,type:str]
    SECRET_OPENAI_API_KEY: ENC[AES256_GCM,data:oSf2gdn6VWxsWMbHl0Azv+ZyMou+SsEad3yK7pDCce+Vl5UuCjgq4p+k6PuMeyXU/2ht+IDrX1p1b4M5WXau9Yx5B/o7h3tbrtx1Kfp552ulKJOsPM7TwoCGvxkXNafSQNkbze22WSsb1jQYsEYdsF5XqFme7uNxP2VKuWMrrMA1CI/FNuuv9xDhifkUQmVBkLQI0s2ogGepIy6CjBMepcCooto=,iv:e/npRP8o2Be8ATjxj7cwVENTmmGWm9CdJmPlFaVQKdo=,tag:H5MNkvs38joMEyFAg2WXVQ==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:w7AbzurxVXRDKw==,iv:pek6hyED7hd98HAuOPt+u4FNsDKfsddvgOvaHfhzuIY=,tag:BVPlTcuuSyt1ckPSUOrDug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-22T20:10:22Z"
    mac: ENC[AES256_GCM,data:hIL3tx7qtrpTubDcPJSYwQCnuNQ2Txv9+RvFOvKLTUNx+Noog745q9wapYqbER/jov7DUGy09n7z2su2vXUhRgXggc0WxnlTTCOJEdufJu5Je28rU8r8N8s19bk9op3h+iT5f9x4mZumVPYJ/aeu96yFZmqHEAa0XBVgFyai5g0=,iv:8nTYcE58km5Yk0uH7YfAu5MgGG/gFABKcY5iFPi0DOs=,tag:kDkEnqD8RZ3vyrmfbB3EcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
