---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-otel-operator
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: "./kubernetes/monitoring/otel/operator"
  targetNamespace: &ns monitoring-otel
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app otel-operator
      app.kubernetes.io/group: monitoring

  postBuild:
    substitute:
      APP: *app
      NS: *ns

  components:
    - ../../../components/ns

  interval: 1h
  prune: true
  retryInterval: 2m
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-storage


# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: otel-stack
#   namespace: flux-system
#   labels: &ll
#     kustomization.flux.home.arpa/default: "true"
#     kustomization.flux.home.arpa/helmpatches: "true"
#     substitution.flux.home.arpa/disabled: "false"
#     prune.flux.home.arpa/disabled: "false"
#     wait.flux.home.arpa/disabled: "false"
#     storage.flux.home.arpa/required: "true"
# spec:
#   targetNamespace: monitoring
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: &app otel-stack
#   path: "./kubernetes/monitoring/otel/stack"
#   postBuild:
#     substituteFrom: []
#     substitute:
#       APP: *app
#   dependsOn: []
