---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-otel-collector
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app otel-collector
  path: "./kubernetes/monitoring/otel/collector"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-gitops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom: []
    substitute:
      APP: *app
  dependsOn: []
    # - name: cluster-apps-otel-operator
