---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
spec:
  accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: "${APP}-bootstrap"
  resources:
    requests:
      storage: "150Gi"
  storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
