apiVersion: v1
kind: Secret
metadata:
    name: postgres-critical-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:s1bNtHNoxfGN1TF3v3HmBtaZ,iv:SfwYDDwX/GifGHYxsslLMOzEpPYPwFedL8AnLoPdLDM=,tag:WPKJEMCxEnJsNTVPn73szA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+fN16+fvfUiBKWGh4zg2UDlwPwwTbtIK9K/n+bdohhgdx3nDM4vXan9whlnwvJ0OIdruy8RWeg==,iv:szwxg97Js4x6lleMUWwoq6z9/7lCiGwm9Ozr4+B96uU=,tag:RgTa7JnBqT3n1EOQkiTdiw==,type:str]
    INIT_POSTGRES_PORT: ENC[AES256_GCM,data:iaAXeA==,iv:3Ypy3u5MOv45iMB2+8EFCHknuMU7IQmrl1ul8lp/CEo=,tag:6z9D0TzzRz3OTnz0ZczCEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-22T03:53:47Z"
    mac: ENC[AES256_GCM,data:F29IydCYWP+qyf27Tut3Ys+MTnIpC01ddq8kSlrI7ZTH5A1c5AfXK5vWuTLKk9SqnPym4mL3B7NsDQrV7QYK0yYhu3HuInohXn7FK5b8ID0TR3nxG3TJzTrZp/rIk+UU70YUnPm/Q0fokp1UFa48ebrLfHa5CaJqFt/RaWjZuI8=,iv:fmPkWR4ecWPnmzHqGC5lkZ60eZaV0F/DpiIIZflcvIk=,tag:kCv4G64Mhn4pHCPggGXq8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
