---
apiVersion: v1
kind: Service
metadata:
  name: postgres-critical
  annotations:
    io.cilium/lb-ipam-ips: ${CLOUDNATIVE_PG_IP}
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-critical-cluster
    role: primary
