---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter-arm64
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.15.3
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: false
    image:
      repository: ghcr.io/joryirving/smartctl_exporter
      tag: "0.14.0"
    nodeSelector:
      kubernetes.io/arch: arm64
    # extraInstances:
    #   - config:
    #       devices:
    #         # TODO - Add all devices here
    #         - /dev/nvme0n1
    #     nodeSelector:
    #       kubernetes.io/arch: arm64
