---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/all.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter-amd64
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.15.4
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    # extraInstances:
    #   - config:
    #       devices:
    #         # TODO - Add all devices here
    #         - /dev/sda
    #         - /dev/sdb
    #         - /dev/sdc
    #         - /dev/sdd
    #         - /dev/sde
    #         - /dev/sdf
    #         - /dev/sdg
    #         - /dev/sdh
    #         - /dev/sdi
    #         - /dev/nvme0n1
    #         - /dev/nvme1n1
    #     nodeSelector:
    #       kubernetes.io/hostname: main.storage
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: false
    nodeSelector:
      kubernetes.io/arch: amd64
