---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease-amd64.yaml
  - ./helmrelease-arm64.yaml
  - ./prometheusrule.yaml
