---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app system-kube-cleanup-operator
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: "./kubernetes/kube-system/kube-cleanup-operator/app/"
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m

