apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:SobaN1xNj51m0YXLdVrU+oa1cwT6/Va1Fhg2Mih+24Q=,iv:0fYbv3Ag8mT8aB/2ndCy6FVn14FaRPPYHZ9/7v8wXww=,tag:HojAjS8gNxfzm3Dcrzn40g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnxm438gfmv6kg658crenxxzad3krnytqqdlseyues9um26meyus7cnla9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM2J5TmZKSEJaV3NuYnQ4
            ckZ4NWlWR1k0Mkg4QlZVK1ZhUFI1TmthOWk0CkJQUTlKWVZjQzhxbVVFY3lLLzJL
            bTMvMzVsMVhPR3JybFRuclh1bGxkZVkKLS0tIHVkNFNRbHpMeDAwSmExUFl2UTRn
            cmVnTCtEaEs3MWxldlUrSUFESWdJeTgKo7fFxvCLOQNKQqC8u0HYeaRrW+i13AUe
            eA2IRWKg6WnWRmNBDXKtOo3/3N+8ZLx2XY4quMBw3NvzZ1of+oFZCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-11T10:54:41Z"
    mac: ENC[AES256_GCM,data:rHp1FeB6ezhyjnRkKwI/rP5mWA32f+Q+ZdODVu2wKXgT4hRFV8vx/sFPk8pebNcTz5Y9O59ZQJ7olnEhoc1MLXiuSdxF436cImxQTxmKKmL7AVm3gIQUK1YNQ8AFOfZx+o35Ph4auEmGtbr3zKV2b7Fz40xDQav2I/qMWPX/DSs=,iv:mR4Re0OIDgVT6LOBKKPWLIkKBye4khrkFHN9sWvKx+s=,tag:33sZ8Gp6uIu1MX4dubigVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
