apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:0xLr5xoYK/qYPn6oia3qsv+ABjMh3pZLJ/Ylneb07SQ=,iv:kAp56I+PWSb4+6twWArYY8x+gUNrmJ15h1p45W0ByE0=,tag:CrcTKbGqp4wni33rq0eMNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RnJKeHBIb0RyVUk5TnBp
            emwweFR5cHowdWxGZE1oRkVDZmZjZ2ROZVdJCm9DSDgwdjBndFZHdzQ3dzlVcHp3
            ZzhRMEY0UWJSOCszaWtNdHVLWUtRUmcKLS0tIFVoNkVteDNmOXo4YlcwQTNtdmh2
            RXFRU0IxTTI1NTlXS3VIYllMMzRhc1EKLeeYDeDWW0+HeE//a7oC6J2mX5nU2sVE
            Lw6FnPTdoW4wsA0Wfv7RYqgL/RVZtbpb73jNXsCWKQaNeTip8q3hwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T00:03:47Z"
    mac: ENC[AES256_GCM,data:KofEU+9tb55zRaM7POkuHkie22DpJJJBbuS1ULtixN//Bw5Nus5qUl4iivD1q47H9V+Ar+OlGeukKgds3kCknap8DsW3W2aIksPbMNm1MwZ/Qc2/AxrWj/PRLWaRgMh1ZiRj4gpoxbl2ayU5PxTn3jIQg/Cs0sDcDiJW+VtKJ3Y=,iv:LdSkFbIaf5cqtNuGCqpWXIdxPt+eM2ZCrUKqXAvDeQc=,tag:HtcJoEbN+Pj7rF70yoXSCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
