---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/network/multus/app"
  postBuild:
    substituteFrom: []
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus-config
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/network/multus/config"
  postBuild:
    substituteFrom: []
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: network-multus
