---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: database-mongodb-mainrs
  namespace: ${NS}
spec:
  members: 1
  type: ReplicaSet
  version: "7.0.16"
  security:
    authentication:
      modes: ["SCRAM", "SCRAM-SHA-1"]
  users:
    - name: mongo
      db: &db admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-secret
        key: MONGO_PASS
      roles:
        - name: clusterAdmin
          db: *db
        - name: userAdminAnyDatabase
          db: *db
        - name: readWriteAnyDatabase
          db: *db
      scramCredentialsSecretName: my-scram
    - name: &lc librechat
      db: *lc
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: librechat-secret
        key: MONGO_PASS
      roles:
        - name: clusterAdmin
          db: *lc
        - name: userAdminAnyDatabase
          db: *lc
        - name: readWriteAnyDatabase
          db: *lc
      scramCredentialsSecretName: my-scram-librechat
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 30Gi
            storageClassName: hl-zfs-pv
        - metadata:
            name: logs-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
            storageClassName: hl-zfs-pv

# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: ${APP}
#   namespace: ${NS}
# spec:
#   interval: 15m
#   chart:
#     spec:
#       chart: mongodb
#       version: 15.1.1
#       sourceRef:
#         kind: HelmRepository
#         name: bitnami
#         namespace: flux-system
#       interval: 15m
#   install:
#     createNamespace: true
#     remediation:
#       retries: 5
#   upgrade:
#     remediation:
#       retries: 5
#   values:
#     persistence:
#       existingClaim: pvc-mongodb
#     auth:
#       enabled: false
#     service:
#       annotations:
#         io.cilium/lb-ipam-ips: "192.168.2.47"
#       externalTrafficPolicy: Cluster
#       # clusterIP: "192.168.2.49"
#       type: LoadBalancer
#     externalAccess:
#       enabled: true
#       service:
#         type: LoadBalancer
#     affinity:
#       nodeAffinity:
#         requiredDuringSchedulingIgnoredDuringExecution:
#             # nodeSelectorTerms:
#             #   - matchExpressions:
#             #       - key: kubernetes.io/arch
#             #         operator: In
#             #         values:
#             #           - amd64
#           nodeSelectorTerms:
#             - matchExpressions:
#                 - key: kubernetes.io/hostname
#                   operator: In
#                   values:
#                     - main.storage
