apiVersion: v1
kind: Secret
metadata:
    name: mongodb-librechat-secrets
    namespace: database-mongodb
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ai-librechat
stringData:
    MONGO_USER: ENC[AES256_GCM,data:V9SQcXtjM1qA,iv:01vAzKiaZQm6/jQ2hFcHy1/ROFnVL0DaXjGsuFXuXCs=,tag:3IidT19xJR9a52d1NjFfHQ==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:UnbJ13QLkXQvmFCHjcV7SrGXKbMcaaqh,iv:ajE3eVNK890fPeQTz30AijQgX2akdeS9AzdcMuHv8bk=,tag:ZcAjlXafz18dn5hsNZhReA==,type:str]
    MONGO_HOST: ENC[AES256_GCM,data:zfOOB/qEgXfNm0z7yyjSMi4WJjRcL7ucLkkgOSGQ/lsCEbjBSRoDevHNe6MUN6p1qGGDahsa3z+lts3rdxc=,iv:3/vVjFUMO7EmkSyNbIq635To8vMrmBxosqtcgLknj1w=,tag:Rdm43R1v39GnBIPUhShY6A==,type:str]
    MONGO_PORT: ENC[AES256_GCM,data:IRn5QMA=,iv:8vs0vpJ309fWFaEFvjexh0DBSC6YsL+s8Sh3eqFs2VA=,tag:wXzf9J8mRB9Ih+6+TJLQWQ==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:sUhZMLAlxxTHa2sjbYQc5nK+7K0gi+ptYUc+V1tT2JmmHk8JIN3fu4zbxxkjuufZQQJRNDUO59NXx49OWOJYgUGnWkxRSQb4D42iOcu5IcoOvvKOGFS3RawiYPVjr49tg0kGiK3gCLlOnJPnfmsk2Mi/2IXCuHVNKg8F,iv:AqpVoCerPaKZJXHCdyYag6EV/V7MkGciQ0gJCwHfLwo=,tag:mmhxaSNarOpUB2bzRbBwwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T20:39:39Z"
    mac: ENC[AES256_GCM,data:rYg8cd/ItrknS7po3ccJVoQJXgBiNptjN8C698j7npwlSitUPuezxjEh9LruXp0Ry6rNpzeofubRMRGRUKcxAFK7fHZ+jvuNgolWkBUAAQgss+xTJ4tW20ROYT6Tr3KVfAf7m35dd9FfWlooGo77VwlcRygfvwxfcaLsFw8LaHY=,iv:6xjIHaWeHn/EuIPCXFtCp49FXnK+ySrKqlR9nkoR8Wg=,tag:VE/lxdowUmaun/pkY3k3AA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
