apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secrets
    namespace: database-mongodb
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ai-librechat
stringData:
    MONGO_USER: ENC[AES256_GCM,data:F8Jsa8Iw0NuZLxI=,iv:7TtkgEOXC5x1Mzjc8UKgmv18KvaqpnlAa9lL2QuEWYs=,tag:BtEzWvtzYvXqOpUfcaheGg==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:jfYl6xwV+N7iIGAJF5rSFFA4XVCHbtCN,iv:JdoGUWE66BKPMlKCfN/lv31gMRzZVpFfDroDy/yaqgc=,tag:l2H7XydR6LXtRMMymmtm6Q==,type:str]
    MONGO_HOST: ENC[AES256_GCM,data:8j+fBkhz6w==,iv:KPopm9DR84/q848VACKtXHAEQ84NVfDSOyT30X5OJww=,tag:IrFgKyr/Js8+p/rdjV12Kw==,type:str]
    MONGO_PORT: ENC[AES256_GCM,data:IRn5QMA=,iv:8vs0vpJ309fWFaEFvjexh0DBSC6YsL+s8Sh3eqFs2VA=,tag:wXzf9J8mRB9Ih+6+TJLQWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTZFelJJeXVpOEV2RGxo
            ZU5zR0JNOVpIL3VuUkN5TzJTM2NQQ0UySUFFCjBQQlI5TGdBVDU0cTZ4NTllOU50
            cDF1WkpQYW9qWTk3cXc1NzMrcDhUTFkKLS0tIDgzdTFoaWtOSnIrNWtwMnBKK3Nk
            SE5KUUdXQUJaR2RZRzRnejNLcUo3cWMKPIpCM+KijrPbBbDyzGeG7EWRogydHKnX
            unGjD1RH6c/dagkxsFRgatWbCtINUlDhnb2gxKBW5En4yjxMCAmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T18:26:53Z"
    mac: ENC[AES256_GCM,data:MJEGjEYpuMVPWzskCyH2DnGbVWK1CHw+7uHYmqEF20LP1g2paMUS76l6bNstU7ypkoVk+w8vtNW+MMqfyr6w6LZ1pCeSO0pr2myXPh/lLVQELvGoossnfYsWCYRXDyXZZco3JP0UzrLVuhBtlTblXXka94+T5o8/cnyoi35fqAs=,iv:0aR59ucsviKZKUhxmzoGMtJVslq+GSq7hANTU+isLaY=,tag:M1uWnUOktWhom2/IewS2LQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
