---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.21.2
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  test:
    enable: true
  values:
    replicaCount: 1
    crds:
      create: true
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
        annotations:
          grafana_folder: Databases
    enableSuperuserAccess: true
    superuserSecret:
      name: superuser-secret
