apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: datastore
    labels:
        cnpg.io/reload: "true"
stringData:
    username: ENC[AES256_GCM,data:0bfKOxXIkaI=,iv:6Ub8qZgLugwE8RnLCp0yzLs81CeclP1UiXf+/JIdUqM=,tag:FbX1DOZKtuYq71MqpvLEvw==,type:str]
    password: ENC[AES256_GCM,data:ZPcwvccwrX9gzHCJbiaD94Ql,iv:RPplRKER7UA7vOkYwE/GoTIBlxB8iueYDZXDgQzz3uQ=,tag:Mjc2firsRQUwYqvjGkVBgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T22:07:48Z"
    mac: ENC[AES256_GCM,data:pVGO+BTQX54NcXc3z5ePVrDXPFRPzdc17WGczihLWplO1biTVbHFfMPVxElXyHkPtGYHh6Znkyx5cOMC18XeBCMj71hBBC0tNIK+tPi/AKIEuQP5vwpbE6gUprLTxgfjTarRDy/ovfGcf4IvT2eqmcbuXaqZyN+Rw9zoLUpbieY=,iv:rQzmt3atsmiPlG1fPnNNscWbOEaqH26/FmkFZYMmGww=,tag:/CAqaKhdpDAKnLXN+e5UYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
