apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    username: ENC[AES256_GCM,data:0bfKOxXIkaI=,iv:6Ub8qZgLugwE8RnLCp0yzLs81CeclP1UiXf+/JIdUqM=,tag:FbX1DOZKtuYq71MqpvLEvw==,type:str]
    password: ENC[AES256_GCM,data:ZPcwvccwrX9gzHCJbiaD94Ql,iv:RPplRKER7UA7vOkYwE/GoTIBlxB8iueYDZXDgQzz3uQ=,tag:Mjc2firsRQUwYqvjGkVBgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-02T01:02:23Z"
    mac: ENC[AES256_GCM,data:BrkSdwdIOqtkfA0xDyIDetfjmHxe/RJvDDS36KS+x2M6UGHZaxNkhQMNFEVvVC8c81++XyK22FJ+GreAS4zPitTNli/a4XWhhNa+TZhzU5WdzIhc7sqszQ1KzRu0pbs0X7r7yl4UU5Z+o9n2yCiRWYYgGq4pbsY0mK4yHo+hBx0=,iv:siIKGf71peeJ6QU/uqficVPNn7MLdcd8X52fkVie5No=,tag:SktZX64OMssjWgVCyrU02g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
