apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:JO5WM5KTIRhVNkWWtnlUsZb8,iv:fS8ksVl4NN+HFmPeaq6r7Zv6HwG+auAH/0VzLFxxtIs=,tag:mTVech7C+gMUVxnV9pvzlw==,type:str]
    username: ENC[AES256_GCM,data:0bfKOxXIkaI=,iv:6Ub8qZgLugwE8RnLCp0yzLs81CeclP1UiXf+/JIdUqM=,tag:FbX1DOZKtuYq71MqpvLEvw==,type:str]
    password: ENC[AES256_GCM,data:ZPcwvccwrX9gzHCJbiaD94Ql,iv:RPplRKER7UA7vOkYwE/GoTIBlxB8iueYDZXDgQzz3uQ=,tag:Mjc2firsRQUwYqvjGkVBgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T14:38:55Z"
    mac: ENC[AES256_GCM,data:lt2B6d4sjK/Jpqky8de7QCDzBV0VkfbSs1riF/I2qJN7EQvi/5XXHW+Flt8MLpU4zVBk7MB9eFGDQwkJKdKD3PuMDVHMnAWO9MlOj8y7qVqVNUDKXMK4VH2RmQgZIrEEhMpl6t2jUWA5HSogiFoFyAZqHrM4wxEJjCLwQSmXsrM=,iv:yJ2L20kZlrfYRE1QZ6vK4AK17AME//MM+T2Vey6aovc=,tag:V5Jff6zlzfumr0gE9oSm4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
