apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: home,monitoring,media
stringData:
    username: ENC[AES256_GCM,data:0bfKOxXIkaI=,iv:6Ub8qZgLugwE8RnLCp0yzLs81CeclP1UiXf+/JIdUqM=,tag:FbX1DOZKtuYq71MqpvLEvw==,type:str]
    password: ENC[AES256_GCM,data:ZPcwvccwrX9gzHCJbiaD94Ql,iv:RPplRKER7UA7vOkYwE/GoTIBlxB8iueYDZXDgQzz3uQ=,tag:Mjc2firsRQUwYqvjGkVBgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pf5un8v27k823gt7dahj3h39zgwk2tr99d30ru2czgyxx6x7fv2spf8x67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFcza2VqMDIzS2RhOXZL
            RThvWmpPeXJ5bVV1MmlpbWxPY1ArLzJGb2tZCjVhNDcvTDFwSEVUeDdrcmFveHhs
            UW13MmFLakdnRzdML0N5UU9zRjBaZk0KLS0tIGVIZDR2WXZHYUZhNDd2UnlTaGxm
            R3crOERmVTV6VW14SmhGemowVytqRGsKpCWigOp3Bbe5LByXZcqjiWVyXpn/FJM4
            VR3H1PbeKY5slOE2QNQWolgBXdERg2Bu2oJGzIbWrccPDck9eS6AeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-21T10:04:44Z"
    mac: ENC[AES256_GCM,data:wfNuNdPZBj5m6U5NF+OLfWiMpU9he/erQ3HfAdXo7kwi4rDrMcoEoK982oCxwc4GIE9X/i9fSzu2Oq6Slxh9M0pt3y9BVj0Y752f4tJBO6P7+h8rXjNUlcQQ9gjaA1Dkl4HmEjj2KRDbcw8PGQNC9jiNAY1eqLEy6isWMQH53AI=,iv:O1dmEDW2SnXnRoMiP1i42Ov1/0zkJbahfNj65PpdgXs=,tag:13bG1tKaNVMi/WsRv2vKxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
