---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor-container-webhook
  namespace: flux-system
spec:
  interval: 1h
  url: https://opensource.indeedeng.io/harbor-container-webhook
